FROM ubuntu:16.04
MAINTAINER Corteggiani Nassim nassim.corteggiani@maximintegrated.com
MAINTAINER Camurai Giovanni giovanni.camurati@eurecom.fr

ARG MAKE_JOBS=16
RUN echo "building using $MAKE_JOBS jobs"

#
#
# Prepare system by installing required packages
#
#
RUN apt-get update && apt-get install -y --force-yes software-properties-common git \
	git make binutils-dev \
	flex bison pkg-config wget nano \
	binutils-arm-none-eabi binutils binutils-dev build-essential\
	python3.5-dev python3-pip\
	sudo libc++-dev libc++1 libedit-dev groff \
	cmake make pkg-config autoconf automake libusb-1.0 usbutils \
	curl libcap-dev libncurses5-dev python-minimal python-pip unzip libusb-1.0-0-dev \
	libboost-all-dev perl zlib1g-dev libnewlib-arm-none-eabi libjsoncpp-dev libjsoncpp1 \
        vim tig

RUN apt-get update && apt-get install -y --force-yes minicom
RUN apt-get update && apt-get install -y --force-yes libc6-dev-i386

RUN apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

#
#
# Fix Ubuntu issues
#
#
#Ubuntu stores json headers into jsoncpp/json but we want json
RUN ln -s /usr/include/jsoncpp/json /usr/include/json

#
#
# Configure system to enable USB device access
#
#
#
RUN mkdir -p /etc/udev/rules.d \
&& touch /etc/udev/rules.d/88-cyusb.rules \
&& echo 'KERNEL=="*", SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ACTION=="add", ATTR{idVendor}=="04b4", MODE="0666"' \
| tee --append /etc/udev/rules.d/88-cyusb.rules

RUN echo ''\
'# This is the main configuration file for Cypress USB FX2 and FX3 devices\n'\
'# All lines beginning with a # in the first column is treated as a comment     \n'\
'# Blank lines are ignored                                                      \n'\
'# Author    - V. Radhakrishnan ( www.atr-labs.com )                            \n'\
'# Copyright - ATR Educational Devices (P) Ltd and Cypress Semiconductors Inc.  \n'\
'# Date      - March 7, 2012                                                    \n'\
'# License   - GPL Version 2                                                    \n'\
'#---------------------------------------------------------------------------   \n'\
'# Location of logfile for the Cypress USB daemon process 'cyusbd'              \n'\
'# Ensure that you have write permission in that directory, if you are non-root.\n'\
'LogFile=cyusbd.log                                                             \n'\
'# Location of PID file for the Cypress USB daemon process 'cyusbd'             \n'\
'# Ensure that you have write permission in that directory, if you are non-root.\n'\
'PIDFile=cyusbd.pid                                                             \n'\
'# Vital Product Data : Vendor/Device IDs - one per line.                       \n'\
'# Format - vendorID	DeviceID	FriendlyName (Max 30 chars or end of line)      \n'\
'<VPD>                                                                          \n'\
'04b4	8613		Default Cypress USB device                                        \n'\
'04b4	4717		Default Cypress USB device                                        \n'\
'04b4	0082		FX2 Device: Custom PID from EEPROM                                \n'\
'04b4	1004		FX2LP Bulk Device                                                 \n'\
'04b4	1003		FX2LP CY-Stream Device                                            \n'\
'04b4	00BC		Cypress Benicia device                                            \n'\
'04b4	00F0		FX3 Example Application                                           \n'\
'04b4	00F1		FX3 Streamer Example                                              \n'\
'04b4	00F3		FX3 Boot-loader                                                   \n'\
'04b4	4720		FX3 I2C/SPI Programmer                                            \n'\
'04b4	1005		FX3 2nd stage boot-loader                                         \n'\
'</VPD>                                                                         \n'\ | tee --append /etc/cyusb.conf


RUN touch /etc/ \
&& echo ''\
'#!/bin/bash               \n'\
'pid=`pidof cyusb_linux`   \n'\
'if [ "$pid" ]; then       \n'\
'    kill -s SIGUSR1 $pid  \n'\
'fi                        \n' | tee --append /usr/local/bin/cy_renumerate.sh \
&& chmod 777 /usr/local/bin/cy_renumerate.sh


# Remove stale versions of the libcyusb library
RUN rm -f /usr/lib/libcyusb.so* /usr/local/lib/libcyusb.so* /usr/lib/x86_64-linux-gnu/libcyusb.so*

# Copy the libcyusb library into the system library folders.
RUN touch libcyusb.so.2 && echo ''\
'f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAA8CQAAAAAAABAAAAAAAAAAHBxAAAAAAAAAAAAAEAAOAAH'\
'AEAAHQAaAAEAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANEwAAAAAAAA0TAAAAAAAAAAA'\
'IAAAAAAAAQAAAAYAAADITQAAAAAAAMhNIAAAAAAAyE0gAAAAAAA4BAAAAAAAANgUAAAAAAAAAAAg'\
'AAAAAAACAAAABgAAAOBNAAAAAAAA4E0gAAAAAADgTSAAAAAAAOABAAAAAAAA4AEAAAAAAAAIAAAA'\
'AAAAAAQAAAAEAAAAyAEAAAAAAADIAQAAAAAAAMgBAAAAAAAAJAAAAAAAAAAkAAAAAAAAAAQAAAAA'\
'AAAAUOV0ZAQAAAAARQAAAAAAAABFAAAAAAAAAEUAAAAAAABsAQAAAAAAAGwBAAAAAAAABAAAAAAA'\
'AABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAA'\
'AFLldGQEAAAAyE0AAAAAAADITSAAAAAAAMhNIAAAAAAAOAIAAAAAAAA4AgAAAAAAAAEAAAAAAAAA'\
'BAAAABQAAAADAAAAR05VAP/YDni0UAKg8CFzvtoURZdE+j3kAAAAACUAAAA+AAAABAAAAAgAAAAG'\
'HIRIg0QYAKqVAggakECJAqArgDh0MumCAQ4BjEYCAz4AAABAAAAAQQAAAEIAAABDAAAARAAAAEYA'\
'AABHAAAAAAAAAAAAAABIAAAAAAAAAEkAAABKAAAATAAAAE4AAABQAAAAUgAAAFMAAABUAAAAVgAA'\
'AAAAAABXAAAAWQAAAFoAAABbAAAAXQAAAAAAAAAAAAAAXgAAAGEAAABkAAAAZQAAAGcAAABoAAAA'\
'aQAAAAAAAAAKyutG72JQ7bWQEfNbNtb/RT/i49lBv07q0+8OTQMlECvCcMbTavO5RyGQSqOtLOoA'\
'G7ZWn2RBKlD43w9BSPq0bGwMfw0gd7i+eIgWsSXMrr99hh2rrpnH4ilzrRfLfWBv48zuJnS/h5Ms'\
'TMPRx6ZJ2XFYHGTPhgi745J8gU+K7QyX1Zt+Sk8Te+P3okJF1ez4+W3sM2FJccmj7q2UEVZlrzQx'\
'bSvuFugf0n494uf0IrmN8Q4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAJAOggAAAAAAAA'\
'AAAAAAAAAAAtCwAAEgAAAAAAAAAAAAAAAAAAAAAAAADiAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADZ'\
'AAAAEgAAAAAAAAAAAAAAAAAAAAAAAABoCwAAEgAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAIAAAAAAA'\
'AAAAAAAAAAAAAAAAAADLAAAAEgAAAAAAAAAAAAAAAAAAAAAAAADNCgAAEgAAAAAAAAAAAAAAAAAA'\
'AAAAAADdAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADoAAAAEgAAAAAAAAAAAAAAAAAAAAAAAABnBQAA'\
'EgAAAAAAAAAAAAAAAAAAAAAAAAC2AAAAEgAAAAAAAAAAAAAAAAAAAAAAAAARBQAAEgAAAAAAAAAA'\
'AAAAAAAAAAAAAADvAAAAEgAAAAAAAAAAAAAAAAAAAAAAAADhAAAAEgAAAAAAAAAAAAAAAAAAAAAA'\
'AABcBwAAEgAAAAAAAAAAAAAAAAAAAAAAAACTBgAAEgAAAAAAAAAAAAAAAAAAAAAAAADuAgAAEgAA'\
'AAAAAAAAAAAAAAAAAAAAAAAMCQAAEgAAAAAAAAAAAAAAAAAAAAAAAACpAAAAEgAAAAAAAAAAAAAA'\
'AAAAAAAAAACtCAAAEgAAAAAAAAAAAAAAAAAAAAAAAADUBwAAEgAAAAAAAAAAAAAAAAAAAAAAAAD1'\
'AgAAEgAAAAAAAAAAAAAAAAAAAAAAAAAuBAAAEgAAAAAAAAAAAAAAAAAAAAAAAABjCwAAEgAAAAAA'\
'AAAAAAAAAAAAAAAAAACwAAAAEgAAAAAAAAAAAAAAAAAAAAAAAAC1BQAAEgAAAAAAAAAAAAAAAAAA'\
'AAAAAADEAAAAEgAAAAAAAAAAAAAAAAAAAAAAAAABAAAAIAAAAAAAAAAAAAAAAAAAAAAAAADSAAAA'\
'EgAAAAAAAAAAAAAAAAAAAAAAAAAfAwAAEgAAAAAAAAAAAAAAAAAAAAAAAADmBgAAEgAAAAAAAAAA'\
'AAAAAAAAAAAAAADGAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABABgAAEgAAAAAAAAAAAAAAAAAAAAAA'\
'AAAmCwAAEgAAAAAAAAAAAAAAAAAAAAAAAACFAwAAEgAAAAAAAAAAAAAAAAAAAAAAAAB9CgAAEgAA'\
'AAAAAAAAAAAAAAAAAAAAAAB7BAAAEgAAAAAAAAAAAAAAAAAAAAAAAADaAwAAEgAAAAAAAAAAAAAA'\
'AAAAAAAAAAB3AgAAEgAAAAAAAAAAAAAAAAAAAAAAAABLCAAAEgAAAAAAAAAAAAAAAAAAAAAAAAD1'\
'BQAAEgAAAAAAAAAAAAAAAAAAAAAAAACXAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAATAwAAEgAAAAAA'\
'AAAAAAAAAAAAAAAAAABaAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAEgAAAAAAAAAAAAAAAAAA'\
'AAAAAADpAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAD7AgAAEgAAAAAAAAAAAAAAAAAAAAAAAADGBAAA'\
'EgAAAAAAAAAAAAAAAAAAAAAAAACjAAAAEgAAAAAAAAAAAAAAAAAAAAAAAAC9AAAAEgAAAAAAAAAA'\
'AAAAAAAAAAAAAABbAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAeCwAAEgAAAAAAAAAAAAAAAAAAAAAA'\
'AABvAAAAEgAAAAAAAAAAAAAAAAAAAAAAAAAaAwAAEgAAAAAAAAAAAAAAAAAAAAAAAADBAgAAEgAA'\
'AAAAAAAAAAAAAAAAAAAAAAAyAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAYCwAAEgAAAAAAAAAAAAAA'\
'AAAAAAAAAABMAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAA1AwAAEgAAAAAAAAAAAAAAAAAAAAAAAAC6'\
'AgAAEQAAAAAAAAAAAAAAAAAAAAAAAADHBQAAEgAMAHk1AAAAAAAAGgAAAAAAAACIBQAAEgAMAFQ1'\
'AAAAAAAAJQAAAAAAAABPAwAAEgAMADc0AAAAAAAANQAAAAAAAADnCgAAEgAMAHs5AAAAAAAAlgMA'\
'AAAAAAD5AwAAEgAMAKE0AAAAAAAAJQAAAAAAAACpAgAAEgAMAPkwAAAAAAAAUAIAAAAAAAAQAAAA'\
'EgANAHRBAAAAAAAAAAAAAAAAAACdAAAAEQAYACRUIAAAAAAABAAAAAAAAABkCQAAEgAMAHY3AAAA'\
'AAAAPgAAAAAAAACUBAAAEgAMAOg0AAAAAAAAIgAAAAAAAACgCQAAEgAMALQ3AAAAAAAAZQAAAAAA'\
'AACgAwAAEgAMAGw0AAAAAAAANQAAAAAAAAAvCQAAEgAMADk3AAAAAAAAPQAAAAAAAAAqBQAAEgAM'\
'ACw1AAAAAAAAKAAAAAAAAACXAAAAEQAYACBUIAAAAAAABAAAAAAAAACvBgAAEgAMANc1AAAAAAAA'\
'IgAAAAAAAADuAQAAEgAMAN0zAAAAAAAALQAAAAAAAABxCAAAEgAMAN02AAAAAAAAGwAAAAAAAABm'\
'AgAAEgAMAGAvAAAAAAAAmQEAAAAAAAAdAgAAEgAMAAo0AAAAAAAALQAAAAAAAAACBwAAEgAMAC42'\
'AAAAAAAANQAAAAAAAADxBwAAEgAMAKA2AAAAAAAAPQAAAAAAAACHAAAAEQAYACBSIAAAAAAAAAEA'\
'AAAAAABHCgAAEgAMAO04AAAAAAAARwAAAAAAAADdBAAAEgAMAAo1AAAAAAAAIgAAAAAAAACPAAAA'\
'EQAYACBTIAAAAAAAAAEAAAAAAACSCgAAEgAMADQ5AAAAAAAARwAAAAAAAADdAgAAEgAMAHMzAAAA'\
'AAAAagAAAAAAAACRCwAAEAAYAABSIAAAAAAAAAAAAAAAAAAdAQAAEgAMAPgrAAAAAAAASAAAAAAA'\
'AACdCwAAEAAYAKBiIAAAAAAAAAAAAAAAAABHBAAAEgAMAMY0AAAAAAAAIgAAAAAAAABKAgAAEgAM'\
'AOQuAAAAAAAAfAAAAAAAAAAyCwAAEgAMAB0+AAAAAAAAVQMAAAAAAADLCAAAEgAMAPg2AAAAAAAA'\
'QQAAAAAAAACKCwAAEAAXAABSIAAAAAAAAAAAAAAAAACaAQAAEgAMAEAsAAAAAAAASAAAAAAAAAAQ'\
'CgAAEgAMAIQ4AAAAAAAAaQAAAAAAAAAJBgAAEgAMAJM1AAAAAAAAIgAAAAAAAABcBgAAEgAMALU1'\
'AAAAAAAAIgAAAAAAAACABwAAEgAMAGM2AAAAAAAAPQAAAAAAAABIAQAAEgAMAPk1AAAAAAAANQAA'\
'AAAAAADIAgAAEgAMAEkzAAAAAAAAKgAAAAAAAADaCQAAEgAMABk4AAAAAAAAawAAAAAAAABgAgAA'\
'EgAJAOggAAAAAAAAAAAAAAAAAAAAX19nbW9uX3N0YXJ0X18AX2ZpbmkAX0lUTV9kZXJlZ2lzdGVy'\
'VE1DbG9uZVRhYmxlAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX19jeGFfZmluYWxpemUAX0p2'\
'X1JlZ2lzdGVyQ2xhc3NlcwBsaWJ1c2JfY29udHJvbF90cmFuc2ZlcgBwaWRmaWxlAGxvZ2ZpbGUA'\
'bG9nZmQAcGlkZmQAZm9wZW4AbWVtc2V0AGZnZXRzAHN0cmxlbgBzdHJ0b2sAc3RyY21wAHN0cmNw'\
'eQBzdHJ0b2wAc3RybmNweQBwcmludGYAZmNsb3NlAF9fc3RhY2tfY2hrX2ZhaWwAbGlidXNiX2dl'\
'dF9kZXZpY2VfZGVzY3JpcHRvcgBfWjE1Y3l1c2JfZ2V0dmVuZG9yUDIwbGlidXNiX2RldmljZV9o'\
'YW5kbGUAX1oyN2N5dXNiX2dldF9kZXZpY2VfZGVzY3JpcHRvclAyMGxpYnVzYl9kZXZpY2VfaGFu'\
'ZGxlUDI0bGlidXNiX2RldmljZV9kZXNjcmlwdG9yAF9aMTZjeXVzYl9nZXRwcm9kdWN0UDIwbGli'\
'dXNiX2RldmljZV9oYW5kbGUAbGlidXNiX2dldF9kZXZpY2VfbGlzdABwdXRzAGxpYnVzYl9vcGVu'\
'AF9aMTljeXVzYl9nZXRfYnVzbnVtYmVyUDIwbGlidXNiX2RldmljZV9oYW5kbGUAX1oxN2N5dXNi'\
'X2dldF9kZXZhZGRyUDIwbGlidXNiX2RldmljZV9oYW5kbGUAX1oxMGN5dXNiX29wZW52AGxpYnVz'\
'Yl9pbml0AF9aMTBjeXVzYl9vcGVudHQAbGlidXNiX29wZW5fZGV2aWNlX3dpdGhfdmlkX3BpZABs'\
'aWJ1c2JfZ2V0X2RldmljZQBfWjExY3l1c2JfZXJyb3JpAHN0ZGVycgBmd3JpdGUAX1oxNWN5dXNi'\
'X2dldGhhbmRsZWkAX1oxMWN5dXNiX2Nsb3NldgBsaWJ1c2JfY2xvc2UAbGlidXNiX2ZyZWVfZGV2'\
'aWNlX2xpc3QAbGlidXNiX2V4aXQAbGlidXNiX2dldF9idXNfbnVtYmVyAGxpYnVzYl9nZXRfZGV2'\
'aWNlX2FkZHJlc3MAX1oyNWN5dXNiX2dldF9tYXhfcGFja2V0X3NpemVQMjBsaWJ1c2JfZGV2aWNl'\
'X2hhbmRsZWgAbGlidXNiX2dldF9tYXhfcGFja2V0X3NpemUAX1oyOWN5dXNiX2dldF9tYXhfaXNv'\
'X3BhY2tldF9zaXplUDIwbGlidXNiX2RldmljZV9oYW5kbGVoAGxpYnVzYl9nZXRfbWF4X2lzb19w'\
'YWNrZXRfc2l6ZQBfWjIzY3l1c2JfZ2V0X2NvbmZpZ3VyYXRpb25QMjBsaWJ1c2JfZGV2aWNlX2hh'\
'bmRsZVBpAGxpYnVzYl9nZXRfY29uZmlndXJhdGlvbgBfWjIzY3l1c2Jfc2V0X2NvbmZpZ3VyYXRp'\
'b25QMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWkAbGlidXNiX3NldF9jb25maWd1cmF0aW9uAF9aMjFj'\
'eXVzYl9jbGFpbV9pbnRlcmZhY2VQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWkAbGlidXNiX2NsYWlt'\
'X2ludGVyZmFjZQBfWjIzY3l1c2JfcmVsZWFzZV9pbnRlcmZhY2VQMjBsaWJ1c2JfZGV2aWNlX2hh'\
'bmRsZWkAbGlidXNiX3JlbGVhc2VfaW50ZXJmYWNlAF9aMzFjeXVzYl9zZXRfaW50ZXJmYWNlX2Fs'\
'dF9zZXR0aW5nUDIwbGlidXNiX2RldmljZV9oYW5kbGVpaQBsaWJ1c2Jfc2V0X2ludGVyZmFjZV9h'\
'bHRfc2V0dGluZwBfWjE2Y3l1c2JfY2xlYXJfaGFsdFAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaABs'\
'aWJ1c2JfY2xlYXJfaGFsdABfWjE4Y3l1c2JfcmVzZXRfZGV2aWNlUDIwbGlidXNiX2RldmljZV9o'\
'YW5kbGUAbGlidXNiX3Jlc2V0X2RldmljZQBfWjI2Y3l1c2Jfa2VybmVsX2RyaXZlcl9hY3RpdmVQ'\
'MjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWkAbGlidXNiX2tlcm5lbF9kcml2ZXJfYWN0aXZlAF9aMjZj'\
'eXVzYl9kZXRhY2hfa2VybmVsX2RyaXZlclAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaQBsaWJ1c2Jf'\
'ZGV0YWNoX2tlcm5lbF9kcml2ZXIAX1oyNmN5dXNiX2F0dGFjaF9rZXJuZWxfZHJpdmVyUDIwbGli'\
'dXNiX2RldmljZV9oYW5kbGVpAGxpYnVzYl9hdHRhY2hfa2VybmVsX2RyaXZlcgBfWjM0Y3l1c2Jf'\
'Z2V0X2FjdGl2ZV9jb25maWdfZGVzY3JpcHRvclAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlUFAyNGxp'\
'YnVzYl9jb25maWdfZGVzY3JpcHRvcgBsaWJ1c2JfZ2V0X2FjdGl2ZV9jb25maWdfZGVzY3JpcHRv'\
'cgBfWjI3Y3l1c2JfZ2V0X2NvbmZpZ19kZXNjcmlwdG9yUDIwbGlidXNiX2RldmljZV9oYW5kbGVo'\
'UFAyNGxpYnVzYl9jb25maWdfZGVzY3JpcHRvcgBsaWJ1c2JfZ2V0X2NvbmZpZ19kZXNjcmlwdG9y'\
'AF9aMzZjeXVzYl9nZXRfY29uZmlnX2Rlc2NyaXB0b3JfYnlfdmFsdWVQMjBsaWJ1c2JfZGV2aWNl'\
'X2hhbmRsZWhQUDIxdXNiX2NvbmZpZ19kZXNjcmlwdG9yAGxpYnVzYl9nZXRfY29uZmlnX2Rlc2Ny'\
'aXB0b3JfYnlfdmFsdWUAX1oyOGN5dXNiX2ZyZWVfY29uZmlnX2Rlc2NyaXB0b3JQMjRsaWJ1c2Jf'\
'Y29uZmlnX2Rlc2NyaXB0b3IAbGlidXNiX2ZyZWVfY29uZmlnX2Rlc2NyaXB0b3IAX1ozM2N5dXNi'\
'X2dldF9zdHJpbmdfZGVzY3JpcHRvcl9hc2NpaVAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaFBoaQBs'\
'aWJ1c2JfZ2V0X3N0cmluZ19kZXNjcmlwdG9yX2FzY2lpAF9aMjBjeXVzYl9nZXRfZGVzY3JpcHRv'\
'clAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaGhQaGkAX1oyN2N5dXNiX2dldF9zdHJpbmdfZGVzY3Jp'\
'cHRvclAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaHRQaGkAX1oyMmN5dXNiX2NvbnRyb2xfdHJhbnNm'\
'ZXJQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWhodHRQaHRqAF9aMThjeXVzYl9jb250cm9sX3JlYWRQ'\
'MjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWhodHRQaHRqAF9aMTljeXVzYl9jb250cm9sX3dyaXRlUDIw'\
'bGlidXNiX2RldmljZV9oYW5kbGVoaHR0UGh0agBfWjE5Y3l1c2JfYnVsa190cmFuc2ZlclAyMGxp'\
'YnVzYl9kZXZpY2VfaGFuZGxlaFBoaVBpaQBsaWJ1c2JfYnVsa190cmFuc2ZlcgBfWjI0Y3l1c2Jf'\
'aW50ZXJydXB0X3RyYW5zZmVyUDIwbGlidXNiX2RldmljZV9oYW5kbGVoUGhpUGlqAGxpYnVzYl9p'\
'bnRlcnJ1cHRfdHJhbnNmZXIAX1oxOGN5dXNiX2Rvd25sb2FkX2Z4MlAyMGxpYnVzYl9kZXZpY2Vf'\
'aGFuZGxlUGNoAHNsZWVwAHN0cnRvdWwAbWFsbG9jAGZyZWUAX1oxOGN5dXNiX2Rvd25sb2FkX2Z4'\
'M1AyMGxpYnVzYl9kZXZpY2VfaGFuZGxlUEtjAHJlYWQAc3RybmNtcABsaWJ1c2ItMS4wLnNvLjAA'\
'bGliYy5zby42AF9lZGF0YQBfX2Jzc19zdGFydABfZW5kAGxpYmN5dXNiLnNvAEdMSUJDXzIuNABH'\
'TElCQ18yLjIuNQAAAAAAAgAAAAIAAgAAAAIAAAACAAIAAAACAAAAAwACAAAAAAAAAAAAAgAAAAAA'\
'AgAAAAIAAgAAAAIAAAACAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAgAC'\
'AAAAAgAAAAIAAgAAAAIAAgAAAAIAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEA'\
'AQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAA'\
'AAAAAQACAIALAAAQAAAAAAAAABRpaQ0AAAMArgsAABAAAAB1GmkJAAACALgLAAAAAAAAyE0gAAAA'\
'AAAIAAAAAAAAAMAlAAAAAAAA0E0gAAAAAAAIAAAAAAAAAIAlAAAAAAAA+FEgAAAAAAAIAAAAAAAA'\
'APhRIAAAAAAAwE8gAAAAAAAGAAAABgAAAAAAAAAAAAAAyE8gAAAAAAAGAAAAVwAAAAAAAAAAAAAA'\
'0E8gAAAAAAAGAAAAVAAAAAAAAAAAAAAA2E8gAAAAAAAGAAAAHQAAAAAAAAAAAAAA4E8gAAAAAAAG'\
'AAAANAAAAAAAAAAAAAAA6E8gAAAAAAAGAAAAOQAAAAAAAAAAAAAA8E8gAAAAAAAGAAAAOwAAAAAA'\
'AAAAAAAA+E8gAAAAAAAGAAAAPQAAAAAAAAAAAAAAGFAgAAAAAAAHAAAAAgAAAAAAAAAAAAAAIFAg'\
'AAAAAAAHAAAAAwAAAAAAAAAAAAAAKFAgAAAAAAAHAAAABAAAAAAAAAAAAAAAMFAgAAAAAAAHAAAA'\
'BQAAAAAAAAAAAAAAOFAgAAAAAAAHAAAATgAAAAAAAAAAAAAAQFAgAAAAAAAHAAAABwAAAAAAAAAA'\
'AAAASFAgAAAAAAAHAAAACAAAAAAAAAAAAAAAUFAgAAAAAAAHAAAACQAAAAAAAAAAAAAAWFAgAAAA'\
'AAAHAAAACgAAAAAAAAAAAAAAYFAgAAAAAAAHAAAACwAAAAAAAAAAAAAAaFAgAAAAAAAHAAAADAAA'\
'AAAAAAAAAAAAcFAgAAAAAAAHAAAADQAAAAAAAAAAAAAAeFAgAAAAAAAHAAAADgAAAAAAAAAAAAAA'\
'gFAgAAAAAAAHAAAADwAAAAAAAAAAAAAAiFAgAAAAAAAHAAAAEAAAAAAAAAAAAAAAkFAgAAAAAAAH'\
'AAAAEQAAAAAAAAAAAAAAmFAgAAAAAAAHAAAAEgAAAAAAAAAAAAAAoFAgAAAAAAAHAAAAEwAAAAAA'\
'AAAAAAAAqFAgAAAAAAAHAAAAFAAAAAAAAAAAAAAAsFAgAAAAAAAHAAAAFQAAAAAAAAAAAAAAuFAg'\
'AAAAAAAHAAAAFgAAAAAAAAAAAAAAwFAgAAAAAAAHAAAAFwAAAAAAAAAAAAAAyFAgAAAAAAAHAAAA'\
'GAAAAAAAAAAAAAAA0FAgAAAAAAAHAAAAGQAAAAAAAAAAAAAA2FAgAAAAAAAHAAAAGgAAAAAAAAAA'\
'AAAA4FAgAAAAAAAHAAAAGwAAAAAAAAAAAAAA6FAgAAAAAAAHAAAAHAAAAAAAAAAAAAAA8FAgAAAA'\
'AAAHAAAAYgAAAAAAAAAAAAAA+FAgAAAAAAAHAAAAWwAAAAAAAAAAAAAAAFEgAAAAAAAHAAAAHgAA'\
'AAAAAAAAAAAACFEgAAAAAAAHAAAAHwAAAAAAAAAAAAAAEFEgAAAAAAAHAAAAIAAAAAAAAAAAAAAA'\
'GFEgAAAAAAAHAAAAIQAAAAAAAAAAAAAAIFEgAAAAAAAHAAAAIgAAAAAAAAAAAAAAKFEgAAAAAAAH'\
'AAAAIwAAAAAAAAAAAAAAMFEgAAAAAAAHAAAAJAAAAAAAAAAAAAAAOFEgAAAAAAAHAAAAJQAAAAAA'\
'AAAAAAAAQFEgAAAAAAAHAAAAJgAAAAAAAAAAAAAASFEgAAAAAAAHAAAAJwAAAAAAAAAAAAAAUFEg'\
'AAAAAAAHAAAAUQAAAAAAAAAAAAAAWFEgAAAAAAAHAAAAKAAAAAAAAAAAAAAAYFEgAAAAAAAHAAAA'\
'KQAAAAAAAAAAAAAAaFEgAAAAAAAHAAAAKgAAAAAAAAAAAAAAcFEgAAAAAAAHAAAAKwAAAAAAAAAA'\
'AAAAeFEgAAAAAAAHAAAALAAAAAAAAAAAAAAAgFEgAAAAAAAHAAAALQAAAAAAAAAAAAAAiFEgAAAA'\
'AAAHAAAALgAAAAAAAAAAAAAAkFEgAAAAAAAHAAAALwAAAAAAAAAAAAAAmFEgAAAAAAAHAAAAZwAA'\
'AAAAAAAAAAAAoFEgAAAAAAAHAAAAMAAAAAAAAAAAAAAAqFEgAAAAAAAHAAAAMQAAAAAAAAAAAAAA'\
'sFEgAAAAAAAHAAAAMgAAAAAAAAAAAAAAuFEgAAAAAAAHAAAAMwAAAAAAAAAAAAAAwFEgAAAAAAAH'\
'AAAANQAAAAAAAAAAAAAAyFEgAAAAAAAHAAAANgAAAAAAAAAAAAAA0FEgAAAAAAAHAAAANwAAAAAA'\
'AAAAAAAA2FEgAAAAAAAHAAAAOAAAAAAAAAAAAAAA4FEgAAAAAAAHAAAASAAAAAAAAAAAAAAA6FEg'\
'AAAAAAAHAAAAOgAAAAAAAAAAAAAA8FEgAAAAAAAHAAAAPAAAAAAAAAAAAAAASIPsCEiLBeUuIABI'\
'hcB0BejjAwAASIPECMMAAAAAAAAAAAAAAAAAAP818i4gAP8l9C4gAA8fQAD/JfIuIABoAAAAAOng'\
'/////yXqLiAAaAEAAADp0P////8l4i4gAGgCAAAA6cD/////JdouIABoAwAAAOmw/////yXSLiAA'\
'aAQAAADpoP////8lyi4gAGgFAAAA6ZD/////JcIuIABoBgAAAOmA/////yW6LiAAaAcAAADpcP//'\
'//8lsi4gAGgIAAAA6WD/////JaouIABoCQAAAOlQ/////yWiLiAAaAoAAADpQP////8lmi4gAGgL'\
'AAAA6TD/////JZIuIABoDAAAAOkg/////yWKLiAAaA0AAADpEP////8lgi4gAGgOAAAA6QD/////'\
'JXouIABoDwAAAOnw/v///yVyLiAAaBAAAADp4P7///8lai4gAGgRAAAA6dD+////JWIuIABoEgAA'\
'AOnA/v///yVaLiAAaBMAAADpsP7///8lUi4gAGgUAAAA6aD+////JUouIABoFQAAAOmQ/v///yVC'\
'LiAAaBYAAADpgP7///8lOi4gAGgXAAAA6XD+////JTIuIABoGAAAAOlg/v///yUqLiAAaBkAAADp'\
'UP7///8lIi4gAGgaAAAA6UD+////JRouIABoGwAAAOkw/v///yUSLiAAaBwAAADpIP7///8lCi4g'\
'AGgdAAAA6RD+////JQIuIABoHgAAAOkA/v///yX6LSAAaB8AAADp8P3///8l8i0gAGggAAAA6eD9'\
'////JeotIABoIQAAAOnQ/f///yXiLSAAaCIAAADpwP3///8l2i0gAGgjAAAA6bD9////JdItIABo'\
'JAAAAOmg/f///yXKLSAAaCUAAADpkP3///8lwi0gAGgmAAAA6YD9////JbotIABoJwAAAOlw/f//'\
'/yWyLSAAaCgAAADpYP3///8lqi0gAGgpAAAA6VD9////JaItIABoKgAAAOlA/f///yWaLSAAaCsA'\
'AADpMP3///8lki0gAGgsAAAA6SD9////JYotIABoLQAAAOkQ/f///yWCLSAAaC4AAADpAP3///8l'\
'ei0gAGgvAAAA6fD8////JXItIABoMAAAAOng/P///yVqLSAAaDEAAADp0Pz///8lYi0gAGgyAAAA'\
'6cD8////JVotIABoMwAAAOmw/P///yVSLSAAaDQAAADpoPz///8lSi0gAGg1AAAA6ZD8////JUIt'\
'IABoNgAAAOmA/P///yU6LSAAaDcAAADpcPz///8lMi0gAGg4AAAA6WD8////JSotIABoOQAAAOlQ'\
'/P///yUiLSAAaDoAAADpQPz///8lGi0gAGg7AAAA6TD8////JfIqIABmkP8lAisgAGaQSI09CS0g'\
'AEiNBQktIABVSCn4SInlSIP4DnYVSIsFriogAEiFwHQJXf/gZg8fRAAAXcMPH0AAZi4PH4QAAAAA'\
'AEiNPcksIABIjTXCLCAAVUgp/kiJ5UjB/gNIifBIweg/SAHGSNH+dBhIiwWJKiAASIXAdAxd/+Bm'\
'Dx+EAAAAAABdww8fQABmLg8fhAAAAAAAgD15LCAAAHUnSIM9XyogAABVSInldAxIiz1aLCAA6EX/'\
'///oSP///13GBVAsIAAB88MPH0AAZi4PH4QAAAAAAEiNPREoIABIgz8AdQvpXv///2YPH0QAAEiL'\
'BQEqIABIhcB06VVIieX/0F3pQP///1VIieVIg+wgSIl9+InQSIlN6ESJReRAiHX0iEXwi0XkD7fI'\
'D7ZF9MHgCInCD7ZF8AnQD7fQSIt16EiLRfho6AMAAFFJifFBuAAAAACJ0boGAAAAvoAAAABIicfo'\
'MP7//0iDxBDJw1VIieVIg+wgSIl9+InQSIlN6ESJReRAiHX0ZolF8ItF5A+3yA+3dfAPtkX0gMwD'\
'D7fQSIt96EiLRfho6AMAAFFJiflBifCJ0boGAAAAvoAAAABIicfo0P3//0iDxBDJw1VIieVIiX3o'\
'iXXkx0X4AQAAAIN95AB1B7gBAAAA60rHRfwAAAAAi0X8O0XkfTiLRfxIY9BIi0XoSAHQD7YAPCB0'\
'HYtF/Ehj0EiLRehIAdAPtgA8CXQJx0X4AAAAAOsHkINF/AHrwItF+F3DVUiJ5VNIgeyoAAAAZEiL'\
'BCUoAAAASIlF6DHASI01PRoAAEiNPTgaAADoAf3//0iJhVD///9Ig71Q////AA+EpgMAAEiNhXD/'\
'//+6eAAAAL4AAAAASInH6MP6//9Ii5VQ////SI2FcP///754AAAASInH6Aj7//9IhcAPlcCEwA+E'\
'UwMAAA+2hXD///88Iw+ELAMAAA+2hXD///88Cg+EIwMAAEiNhXD///9Iicfo7fn//4nCSI2FcP//'\
'/4nWSInH6ND+//+FwA+VwITAD4X6AgAASI2FcP///0iNNZEZAABIicfoV/z//0iJhVj///9Ii4VY'\
'////SI01eRkAAEiJx+ia+v//hcB1NkiNNW4ZAAC/AAAAAOgl/P//SImFYP///0iLhWD///9IicZI'\
'iwV1JyAASInH6BX5///pHf///0iLhVj///9IjTU1GQAASInH6Er6//+FwHU2SI01HhkAAL8AAAAA'\
'6NX7//9IiYVg////SIuFYP///0iJxkiLBS0nIABIicfoxfj//+nN/v//SIuFWP///0iNNe0YAABI'\
'icfo+vn//4XAD4XuAQAASIuVUP///0iNhXD///++eAAAAEiJx+i3+f//SIXAD5XAhMAPhIb+//8P'\
'toVw////PCMPhJ4BAAAPtoVw////PAoPhJUBAABIjYVw////SInH6Jz4//+JwkiNhXD///+J1kiJ'\
'x+h//f//hcAPlcCEwA+FbAEAAIsFPjkgAIP4Yw+EYwEAAEiNhXD///9IjTU+GAAASInH6Pf6//9I'\
'iYVY////SIuFWP///0iNNTMYAABIicfoOvn//4XAD4RlAQAASI01IxgAAL8AAAAA6MH6//9IiYVg'\
'////SI018hcAAL8AAAAA6Kn6//9IiYVo////ix3EOCAASIuFWP///7oQAAAAvgAAAABIicfoE/n/'\
'/4nBSGPDSAHASInCSMHiBEgBwkiNBUorIABmiQwCix2IOCAASIuFYP///7oQAAAAvgAAAABIicfo'\
'1/j//4nBSGPDSAHASInCSMHiBEgBwkiNBRArIABmiQwCiwVMOCAASJhIAcBIicJIweIESAHQSI0V'\
'7iogAEgB0EiNSARIi4Vo////uh4AAABIicZIic/o0Pb//4sFEjggAEiYSAHASInCSMHiBEgBwkiN'\
'BdUqIADGBAIAiwXyNyAAg8ABiQXpNyAA6Sr+//+Q6ST+//+Q6R7+//+Q6Rj+//+Q6RL+//9IjYVw'\
'////SInGSI098xYAALgAAAAA6Bn3//+/AQAAAOiv+f//kOmW/P//kOmQ/P//kOmK/P//kOmE/P//'\
'SIuFUP///0iJx+iY9v//6wGQSItF6GRIMwQlKAAAAHQF6MH2//9IgcSoAAAAW13DVUiJ5UiD7EBI'\
'iX3IZEiLBCUoAAAASIlF+DHAx0XUAAAAAEiNVeBIi0XISInWSInH6KL4//8Pt0XqD7fAiUXYD7dF'\
'6g+3wIlF3MdF0AAAAACLBQk3IAA5RdB9W4tF0EiYSAHASInCSMHiBEgBwkiNBaMpIAAPtxQCD7dF'\
'6GY5wnUvi0XQSJhIAcBIicJIweIESAHCSI0FfykgAA+3FAIPt0XqZjnCdQnHRdQBAAAA6waDRdAB'\
'65qLRdRIi034ZEgzDCUoAAAAdAXo6vX//8nDVUiJ5UiD7DBIiX3YZEiLBCUoAAAASIlF+DHASI1V'\
'4EiLRdhIidZIicfo+vf//w+3RehIi034ZEgzDCUoAAAAdAXoovX//8nDVUiJ5UiD7DBIiX3YZEiL'\
'BCUoAAAASIlF+DHASI1V4EiLRdhIidZIicfosvf//w+3RepIi034ZEgzDCUoAAAAdAXoWvX//8nD'\
'VUiJ5VNIg+w4SMdF2AAAAABIx0XgAAAAAMdF0AAAAABIjTXhNSAAvwAAAADoZ/b//4kFzTUgAIsF'\
'xzUgAIXAeRZIjT0gFQAA6Lv0//+4/P///+n+AQAAxwVHKCAAAAAAAMdFzAAAAACLBZY1IAA5RcwP'\
'jdgBAABIiwWKNSAAi1XMSGPSSMHiA0gB0EiLAEiJRehIi0XoSInH6AP+//+FwA+VwITAD4SbAQAA'\
'iwX3JyAASGPQSInQSAHASAHQSMHgA0iJwUiNBe0mIABIi1XoSIkUAYsFzycgAEhj0EiJ0EgBwEgB'\
'0EjB4ANIjRXIJiAASAHQSI1QCEiLRehIidZIicfoovP//4lF1IN91AB0FkiNPXsUAADo7fP//7j7'\
'////6TABAACLBX0nIABIY9BIidBIAcBIAdBIweADSInCSI0FeyYgAEiLBAJIiUXgix1VJyAASItF'\
'4EiJx+j59P//icFIY9NIidBIAcBIAdBIweADSInCSI0FTSYgAGaJDAKLHSMnIABIi0XgSInH6Lf0'\
'//+JwUhj00iJ0EgBwEgB0EjB4ANIicJIjQUdJiAAZokMAosF8SYgAEhj0EiJ0EgBwEgB0EjB4ANI'\
'icJIjQX7JSAAxgQCAYsdzSYgAEiLReBIicfo8fL//4nBSGPTSInQSAHASAHQSMHgA0iJwkiNBcol'\
'IACIDAKLHZwmIABIi0XgSInH6PD0//+JwUhj00iJ0EgBwEgB0EjB4ANIicJIjQWaJSAAiAwCiwVr'\
'JiAAg8ABiQViJiAAg0XMAekZ/v//iwVTJiAASIPEOFtdw1VIieVIg+wQvgAAAABIjT2KEgAAuAAA'\
'AADoDvX//4lF+IN9+AB5E0iNPSYTAADoefL//7j/////60CLRfiJx+hI8///6PT3//+/AAAAAOi5'\
'9P//iUX8g338AHQTSI09GRMAAOhE8v//uP7////rC+gw/f//iUX8i0X8ycNVSInlU0iD7CiJ+onw'\
'ZolV3GaJRdhIx0XoAAAAAL8AAAAA6Gn0//+JReSDfeQAdBZIjT3JEgAA6PTx//+4/////+lMAQAA'\
'D7dV2A+3RdyJxr8AAAAA6Obz//9IiUXoSIN96AB1FkiNPbwSAADov/H//7j+////6RcBAABIi0Xo'\
'SInH6Onz//9IiQVSJCAASItF6EiJBU8kIACLHTElIABIi0XoSInH6NXy//+JwUhj00iJ0EgBwEgB'\
'0EjB4ANIicJIjQUpJCAAZokMAosd/yQgAEiLRehIicfok/L//4nBSGPTSInQSAHASAHQSMHgA0iJ'\
'wkiNBfkjIABmiQwCiwXNJCAASGPQSInQSAHASAHQSMHgA0iJwkiNBdcjIADGBAIBix2pJCAASItF'\
'6EiJx+jN8P//icFIY9NIidBIAcBIAdBIweADSInCSI0FpiMgAIgMAosdeCQgAEiLRehIicfozPL/'\
'/4nBSGPTSInQSAHASAHQSMHgA0iJwkiNBXYjIACIDALHBUMkIAABAAAAuAEAAABIg8QoW13DVUiJ'\
'5UiD7BCJffyDffz/dShIiwXnHiAASIsASInBuhMAAAC+AQAAAEiNPXERAADoc/P//+kUAgAAg338'\
'/nUoSIsFuR4gAEiLAEiJwboSAAAAvgEAAABIjT1XEQAA6EXz///p5gEAAIN9/P11KEiLBYseIABI'\
'iwBIicG6KQAAAL4BAAAASI09PBEAAOgX8///6bgBAACDffz8dShIiwVdHiAASIsASInBuiEAAAC+'\
'AQAAAEiNPT4RAADo6fL//+mKAQAAg338+3UoSIsFLx4gAEiLAEiJwboRAAAAvgEAAABIjT0yEQAA'\
'6Lvy///pXAEAAIN9/Pp1KEiLBQEeIABIiwBIicG6DgAAAL4BAAAASI09FhEAAOiN8v//6S4BAACD'\
'ffz5dShIiwXTHSAASIsASInBuhQAAAC+AQAAAEiNPfcQAADoX/L//+kAAQAAg338+HUoSIsFpR0g'\
'AEiLAEiJwboJAAAAvgEAAABIjT3eEAAA6DHy///p0gAAAIN9/Pd1KEiLBXcdIABIiwBIicG6CwAA'\
'AL4BAAAASI09uhAAAOgD8v//6aQAAACDffz2dSVIiwVJHSAASIsASInBui0AAAC+AQAAAEiNPZoQ'\
'AADo1fH//+t5g3389XUlSIsFHh0gAEiLAEiJwboUAAAAvgEAAABIjT2dEAAA6Krx///rToN9/Ax1'\
'JUiLBfMcIABIiwBIicG6JAAAAL4BAAAASI09jBAAAOh/8f//6yNIiwXOHCAASIsASInBuhcAAAC+'\
'AQAAAEiNPYwQAADoWvH//5DJw1VIieWJffyLRfxIY9BIidBIAcBIAdBIweADSInCSI0F2yAgAEiL'\
'BAJdw1VIieVIg+wQx0X8AAAAAIsFqCEgADlF/H0vi0X8SGPQSInQSAHASAHQSMHgA0iJwkiNBZ4g'\
'IABIiwQCSInH6Gru//+DRfwB68ZIiwXNLiAAvgEAAABIicfoYPD//78AAAAA6Abw//+QycNVSInl'\
'SIPsIEiJfehIi0XoSInH6Nvv//9IiUX4SItF+EiJx+j77v//D7bAycNVSInlSIPsIEiJfehIi0Xo'\
'SInH6K7v//9IiUX4SItF+EiJx+ie8P//D7bAycNVSInlSIPsIEiJfeiJ8IhF5EiLRehIicfofO//'\
'/0iJRfgPtlXkSItF+InWSInH6Obu///Jw1VIieVIg+wgSIl96InwiEXkSItF6EiJx+hH7///SIlF'\
'+A+2VeRIi0X4idZIicfo4e7//8nDVUiJ5UiD7BBIiX34SIl18EiLVfBIi0X4SInWSInH6Lzt///J'\
'w1VIieVIg+wQSIl9+Il19ItV9EiLRfiJ1kiJx+iK7v//ycNVSInlSIPsEEiJffiJdfSLVfRIi0X4'\
'idZIicfoOO///8nDVUiJ5UiD7BBIiX34iXX0i1X0SItF+InWSInH6Kbs///Jw1VIieVIg+wQSIl9'\
'+Il19IlV8ItV8ItN9EiLRfiJzkiJx+he7P//ycNVSInlSIPsEEiJffiJ8IhF9A+2VfRIi0X4idZI'\
'icfoOe3//8nDVUiJ5UiD7BBIiX34SItF+EiJx+gv7v//ycNVSInlSIPsEEiJffiJdfSLVfRIi0X4'\
'idZIicfofe3//8nDVUiJ5UiD7BBIiX34iXX0i1X0SItF+InWSInH6Dvs///Jw1VIieVIg+wQSIl9'\
'+Il19ItV9EiLRfiJ1kiJx+gZ7f//ycNVSInlSIPsIEiJfehIiXXgSItF6EiJx+i77f//SIlF+EiL'\
'VeBIi0X4SInWSInH6NTt///Jw1VIieVIg+wgSIl96EiJdeBIi0XoSInH6Ibt//9IiUX4SItV4EiL'\
'RfhIidZIicfon+v//8nDVUiJ5UiD7DBIiX3oifBIiVXYiEXkSItF6EiJx+hM7f//SIlF+A+2TeRI'\
'i1XYSItF+InOSInH6MLr///Jw1VIieVIg+wwSIl96InwSIlV2IhF5EiLRehIicfoD+3//0iJRfgP'\
'tk3kSItV2EiLRfiJzkiJx+jV7P//ycNVSInlSIPsEEiJffhIi0X4SInH6Fvr//+QycNVSInlSIPs'\
'MEiJfeiJ8EiJVdiJTeCIReRIi0XoSInH6LTs//9IiUX4D7Z15ItN4EiLVdhIi0XoSInH6Pnq///J'\
'w1VIieVIg+wgSIl9+InQSIlN6ESJReRAiHX0iEXwD7ZV8A+2dfSLfeRIi03oSItF+EGJ+EiJx+h8'\
'7v//ycNVSInlSIPsIEiJffiJ0EiJTehEiUXkQIh19GaJRfAPt1XwD7Z19It95EiLTehIi0X4QYn4'\
'SInH6KTu///Jw1VIieVIg+wwSIl9+In3idaJykSJwUyJTeCLRRBAiH30QIh18GaJVexmiU3oZolF'\
'3A+3fdxED7dV6A+3TewPtlXwD7Z19EyLTeBIi0X4RItFGEFQV0WJ0EiJx+ht7P//SIPEEMnDVUiJ'\
'5UiD7DBIiX34ifeJ1onKRInBTIlN4ItFEECIffRAiHXwZolV7GaJTehmiUXcD7d93EQPt1XoD7dN'\
'7A+2VfAPtkX0g8iAD7bwTItN4EiLRfhEi0UYQVBXRYnQSInH6ALs//9Ig8QQycNVSInlSIPsMEiJ'\
'ffiJ94nWicpEicFMiU3gi0UQQIh99ECIdfBmiVXsZolN6GaJRdwPt3XcRA+3RegPt03sD7ZV8A+2'\
'RfSD4H9BicJMi03gSItF+It9GFdWRInWSInH6Jnr//9Ig8QQycNVSInlSIPsMEiJffiJ8EiJVeiJ'\
'TfBMiUXgRIlN3IhF9ESLRdwPtnX0SIt94ItN8EiLVehIi0X4RYnBSYn4SInH6C7q///Jw1VIieVI'\
'g+wwSIl9+InwSIlV6IlN8EyJReBEiU3ciEX0D7Z19ESLRdxIi33gi03wSItV6EiLRfhFicFJifhI'\
'icfoB+j//8nDVUiJ5VNIgeyIAQAASIm9iP7//0iJtYD+//+J0IiFfP7//2RIiwQlKAAAAEiJRegx'\
'wEjHhaD+//8AAAAAxoWQ/v//AMeFlP7//wAAAADGhZH+//8AZseFkv7//wAASMeFqP7//wAAAABI'\
'i4WA/v//SI01jwcAAEiJx+hX6v//SImFoP7//8aFsv7//wDGhdT+//8AxoXC/v//AMaFkP7//wFI'\
'jZWQ/v//SIuFiP7//2joAwAAagFJidFBuAAAAAC5AOYAALqgAAAAvkAAAABIicfoX+r//0iDxBCJ'\
'hZz+//+DvZz+//8AdRdIjT16CQAA6CDn//+LhZz+///pfAIAAL8BAAAA6Dvq///HhZT+//8AAAAA'\
'SIuVoP7//0iNheD+//++AAEAAEiJx+j25///SIXAD5XAhMAPhMIBAAAPtoXo/v//PDEPhLIBAABI'\
'jYXg/v//SIPAAUiNjbD+//+6AgAAAEiJxkiJz+hX5v//SI2FsP7//7oQAAAAvgAAAABIicfobun/'\
'/4iFkf7//0iNheD+//9Ig8ADSI2N0P7//7oEAAAASInGSInP6Bbm//9IjYXQ/v//uhAAAAC+AAAA'\
'AEiJx+gt6f//ZomFkv7//w+2hZH+//9Iicfo5+f//0iJhaj+///HhZj+//8AAAAAD7aFkf7//zuF'\
'mP7//35ni4WY/v//AcCDwAlIjZXg/v//SJhIjQwCSI2FwP7//7oCAAAASInOSInH6Jjl//+LhZj+'\
'//9IY9BIi4Wo/v//SI0cAkiNhcD+//+6EAAAAL4AAAAASInH6Jvo//+IA4OFmP7//wHrig+2tZH+'\
'//8Pt42S/v//D7aVfP7//0iLvaj+//9Ii4WI/v//aOgDAABWSYn5QbgAAAAAvkAAAABIicfokej/'\
'/0iDxBCJhZz+//+DvZz+//8AdSZIjT2sBwAA6FLl//9Ii4Wo/v//SInH6NPk//+LhZz+///pnwAA'\
'AA+2hZH+//8BhZT+//9Ii4Wo/v//SInH6Kzk///pFv7//5CLhZT+//+JxkiNPXYHAAC4AAAAAOhd'\
'5f//vwEAAADoI+j//8aFkP7//wBIjZWQ/v//SIuFiP7//2joAwAAagFJidFBuAAAAAC5AOYAALqg'\
'AAAAvkAAAABIicfo1+f//0iDxBCJhZz+//9Ii4Wg/v//SInH6K7k//+4AAAAAEiLXehkSDMcJSgA'\
'AAB0BejV5P//SItd+MnDVUiJ5UiD7EBIiX3YiXXUSIlVyIlN0ItF0IlF8EiLRchIiUX4x0XsAAAA'\
'AIN98AAPjpAAAACBffAAEAAAfgnHRegAEAAA6waLRfCJReiLRegPt8iLRexIY9BIi0XISI00AotF'\
'1MHoEInHi0XUD7fQSItF2GjoAwAAUUmJ8UGJ+InRuqAAAAC+QAAAAEiJx+gM5///SIPEEIlF9ItF'\
'9DtF6HQMSI09KwYAAOjR4///i0XoAUXUi0XoKUXwi0XoAUXs6Wb////HReQAAAAAi0XQjVADhcAP'\
'SMLB+AI7ReR+KotF5EiYSI0UhQAAAABIi0X4SAHQixCLBYwkIAAB0IkFhCQgAINF5AHrw5DJw1VI'\
'ieVIgeyQQg8ASIm9eL3w/0iJtXC98P9kSIsEJSgAAABIiUX4McBIx4WgvfD/AAAAAEiLhXC98P++'\
'AAAAAEiJx7gAAAAA6Kfl//+JhYS98P+DvYS98P8AeRZIjT2dBQAA6Azj//+4/////+nOAgAASI09'\
'lgUAAOj24v//x4WIvfD/AAAAAMcF6iMgAAAAAABIjY2wvfD/i4WEvfD/ugIAAABIic6Jx+jG4///'\
'iYWMvfD/SI2FsL3w/7oCAAAASI01YQUAAEiJx+hl4v//hcB0FkiNPVIFAADoleL//7j+////6VcC'\
'AABIjY2wvfD/i4WEvfD/ugEAAABIic6Jx+hv4///iYWMvfD/D7aFsL3w/w+2wIPgAYXAdBZIjT05'\
'BQAA6Ezi//+4/f///+kOAgAASI2NsL3w/4uFhL3w/7oBAAAASInOicfoJuP//4mFjL3w/w+2hbC9'\
'8P88sHQWSI09HgUAAOgJ4v//uPz////pywEAAEiNjbC98P+LhYS98P+6BAAAAEiJzonH6OPi//+J'\
'hYy98P9IjYWwvfD/SImFoL3w/0iLhaC98P+LAImFkL3w/0iNjbC98P+LhYS98P+6BAAAAEiJzonH'\
'6KTi//+JhYy98P9IjYWwvfD/SImFqL3w/0iLhai98P+LAImFlL3w/4O9kL3w/wB0V4uFkL3w/8Hg'\
'Akhj0EiNjbC98P+LhYS98P9Iic6Jx+hV4v//iYWMvfD/i4WQvfD/jQyFAAAAAEiNlbC98P+LtZS9'\
'8P9Ii4V4vfD/SInH6Kf8///pIv///4uFlL3w/4mFmL3w/5BIjY2wvfD/i4WEvfD/ugQAAABIic6J'\
'x+j44f//iYWMvfD/SI2FsL3w/0iJhaC98P9Ii4WgvfD/ixCLBd0hIAA5wnQWSI09/wMAAOjF4P//'\
'uPv////phwAAAL8BAAAA6OHj//+LhZi98P/B6BCJwYuFmL3w/w+30EiLhXi98P9o6AMAAGoAQbkA'\
'AAAAQYnIidG6oAAAAL5AAAAASInH6JLj//9Ig8QQiYWcvfD/g72cvfD/AHQZi4WcvfD/icZIjT2Y'\
'AwAAuAAAAADopuD//4uFhL3w/4nH6Bnh//+4AAAAAEiLdfhkSDM0JSgAAAB0Behw4P//ycMAAEiD'\
'7AhIg8QIwwAAAHIAL2V0Yy9jeXVzYi5jb25mACA9CQoATG9nRmlsZQAgCQoAUElERmlsZQA8VlBE'\
'PgA8L1ZQRD4AIAkAAAAAAABFcnJvciBpbiBjb25maWcgZmlsZSAvZXRjL2N5dXNiLmNvbmY6ICVz'\
'IAoAAAAAAABMaWJyYXJ5OiBFcnJvciBpbiBlbnVtZXJhdGluZyBkZXZpY2VzLi4uAEVycm9yIGlu'\
'IG9wZW5pbmcgZGV2aWNlAAAAAAAAAAAvZXRjL2N5dXNiLmNvbmYgZmlsZSBub3QgZm91bmQuIEV4'\
'aXRpbmcARXJyb3IgaW4gaW5pdGlhbGl6aW5nIGxpYnVzYiBsaWJyYXJ5Li4uAERldmljZSBub3Qg'\
'Zm91bmQASW5wdXQvb3V0cHV0IGVycm9yCgBJbnZhbGlkIHBhcmFtZXRlcgoAQWNjZXNzIGRlbmll'\
'ZCAoaW5zdWZmaWNpZW50IHBlcm1pc3Npb25zKQoAAAAAAAAATm8gc3VjaCBkZXZpY2UuIERpc2Nv'\
'bm5lY3RlZC4uLj8KAEVudGl0eSBub3QgZm91bmQKAFJlc291cmNlIGJ1c3kKAE9wZXJhdGlvbiB0'\
'aW1lZCBvdXQKAE92ZXJmbG93CgBQaXBlIGVycm9yCgAAAFN5c3RlbSBjYWxsIGludGVycnVwdGVk'\
'LCAoIGR1ZSB0byBzaWduYWwgPyApCgBJbnN1ZmZpY2llbnQgbWVtb3J5CgAAAAAAAE9wZXJhdGlv'\
'biBub3Qgc3VwcG9ydGVkL2ltcGxlbWVudGVkCgBVbmtub3duIGludGVybmFsIGVycm9yCgBFcnJv'\
'ciBpbiBjb250cm9sX3RyYW5zZmVyAFRvdGFsIGJ5dGVzIGRvd25sb2FkZWQgPSAlZAoARmlsZSBu'\
'b3QgZm91bmQARmlsZSBzdWNjZXNzZnVsbHkgb3BlbmVkAENZAABJbWFnZSBkb2VzIG5vdCBoYXZl'\
'ICdDWScgYXQgc3RhcnQuIGFib3J0aW5nAAAAAABJbWFnZSBkb2VzIG5vdCBjb250YWluIGV4ZWN1'\
'dGFibGUgY29kZQAATm90IGEgbm9ybWFsIEZXIGJpbmFyeSB3aXRoIGNoZWNrc3VtAEVycm9yIGlu'\
'IGNoZWNrc3VtAABJZ25vcmVkIGVycm9yIGluIGNvbnRyb2xfdHJhbnNmZXI6ICVkCgAAARsDO2wB'\
'AAAsAAAAENz//4gBAADw4P//sAEAAFbh///QAQAAtuH///ABAAAh4v//EAIAACnm//84AgAA+Ob/'\
'/1gCAABA5///eAIAAIjn//+YAgAA5On//8ACAABg6v//4AIAAPnr//8IAwAASe7//ygDAABz7v//'\
'SAMAAN3u//9oAwAACu///4gDAAA37///qAMAAGzv///IAwAAoe///+gDAADG7///CAQAAOjv//8o'\
'BAAACvD//0gEAAAs8P//aAQAAFTw//+IBAAAefD//6gEAACT8P//yAQAALXw///oBAAA1/D//wgF'\
'AAD58P//KAUAAC7x//9IBQAAY/H//2gFAACg8f//iAUAAN3x//+oBQAA+PH//8gFAAA58v//6AUA'\
'AHby//8IBgAAtPL//ygGAAAZ8///SAYAAITz//9oBgAA7fP//4gGAAA09P//qAYAAHv0///IBgAA'\
'Efj///AGAAAd+f//EAcAAAAAAAAUAAAAAAAAAAF6UgABeBABGwwHCJABAAAkAAAAHAAAAIDa///Q'\
'AwAAAA4QRg4YSg8LdwiAAD8aOyozJCIAAAAAHAAAAEQAAAA43///ZgAAAABBDhCGAkMNBgJhDAcI'\
'AAAcAAAAZAAAAH7f//9gAAAAAEEOEIYCQw0GAlsMBwgAABwAAACEAAAAvt///2sAAAAAQQ4QhgJD'\
'DQYCZgwHCAAAJAAAAKQAAAAJ4P//CAQAAABBDhCGAkMNBkiDAwP7AwwHCAAAAAAAABwAAADMAAAA'\
'6eP//88AAAAAQQ4QhgJDDQYCygwHCAAAHAAAAOwAAACY5P//SAAAAABBDhCGAkMNBgJDDAcIAAAc'\
'AAAADAEAAMDk//9IAAAAAEEOEIYCQw0GAkMMBwgAACQAAAAsAQAA6OT//1wCAAAAQQ4QhgJDDQZF'\
'gwMDUgIMBwgAAAAAAAAcAAAAVAEAABzn//98AAAAAEEOEIYCQw0GAncMBwgAACQAAAB0AQAAeOf/'\
'/5kBAAAAQQ4QhgJDDQZFgwMDjwEMBwgAAAAAAAAcAAAAnAEAAOno//9QAgAAAEEOEIYCQw0GA0sC'\
'DAcIABwAAAC8AQAAGev//yoAAAAAQQ4QhgJDDQZlDAcIAAAAHAAAANwBAAAj6///agAAAABBDhCG'\
'AkMNBgJlDAcIAAAcAAAA/AEAAG3r//8tAAAAAEEOEIYCQw0GaAwHCAAAABwAAAAcAgAAeuv//y0A'\
'AAAAQQ4QhgJDDQZoDAcIAAAAHAAAADwCAACH6///NQAAAABBDhCGAkMNBnAMBwgAAAAcAAAAXAIA'\
'AJzr//81AAAAAEEOEIYCQw0GcAwHCAAAABwAAAB8AgAAsev//yUAAAAAQQ4QhgJDDQZgDAcIAAAA'\
'HAAAAJwCAAC26///IgAAAABBDhCGAkMNBl0MBwgAAAAcAAAAvAIAALjr//8iAAAAAEEOEIYCQw0G'\
'XQwHCAAAABwAAADcAgAAuuv//yIAAAAAQQ4QhgJDDQZdDAcIAAAAHAAAAPwCAAC86///KAAAAABB'\
'DhCGAkMNBmMMBwgAAAAcAAAAHAMAAMTr//8lAAAAAEEOEIYCQw0GYAwHCAAAABwAAAA8AwAAyev/'\
'/xoAAAAAQQ4QhgJDDQZVDAcIAAAAHAAAAFwDAADD6///IgAAAABBDhCGAkMNBl0MBwgAAAAcAAAA'\
'fAMAAMXr//8iAAAAAEEOEIYCQw0GXQwHCAAAABwAAACcAwAAx+v//yIAAAAAQQ4QhgJDDQZdDAcI'\
'AAAAHAAAALwDAADJ6///NQAAAABBDhCGAkMNBnAMBwgAAAAcAAAA3AMAAN7r//81AAAAAEEOEIYC'\
'Qw0GcAwHCAAAABwAAAD8AwAA8+v//z0AAAAAQQ4QhgJDDQZ4DAcIAAAAHAAAABwEAAAQ7P//PQAA'\
'AABBDhCGAkMNBngMBwgAAAAcAAAAPAQAAC3s//8bAAAAAEEOEIYCQw0GVgwHCAAAABwAAABcBAAA'\
'KOz//0EAAAAAQQ4QhgJDDQZ8DAcIAAAAHAAAAHwEAABJ7P//PQAAAABBDhCGAkMNBngMBwgAAAAc'\
'AAAAnAQAAGbs//8+AAAAAEEOEIYCQw0GeQwHCAAAABwAAAC8BAAAhOz//2UAAAAAQQ4QhgJDDQYC'\
'YAwHCAAAHAAAANwEAADJ7P//awAAAABBDhCGAkMNBgJmDAcIAAAcAAAA/AQAABTt//9pAAAAAEEO'\
'EIYCQw0GAmQMBwgAABwAAAAcBQAAXe3//0cAAAAAQQ4QhgJDDQYCQgwHCAAAHAAAADwFAACE7f//'\
'RwAAAABBDhCGAkMNBgJCDAcIAAAkAAAAXAUAAKvt//+WAwAAAEEOEIYCQw0GSIMDA4kDDAcIAAAA'\
'AAAAHAAAAIQFAAAZ8f//DAEAAABBDhCGAkMNBgMHAQwHCAAcAAAApAUAAAXy//9VAwAAAEEOEIYC'\
'Qw0GA1ADDAcIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAMAlAAAAAAAAgCUAAAAAAAAAAAAAAAAAAAEAAAAAAAAAcAsAAAAA'\
'AAABAAAAAAAAAIALAAAAAAAADgAAAAAAAACiCwAAAAAAAAwAAAAAAAAA6CAAAAAAAAANAAAAAAAA'\
'AHRBAAAAAAAAGQAAAAAAAADITSAAAAAAABsAAAAAAAAACAAAAAAAAAAaAAAAAAAAANBNIAAAAAAA'\
'HAAAAAAAAAAIAAAAAAAAAPX+/28AAAAA8AEAAAAAAAAFAAAAAAAAAHANAAAAAAAABgAAAAAAAABo'\
'AwAAAAAAAAoAAAAAAAAAxAsAAAAAAAALAAAAAAAAABgAAAAAAAAAAwAAAAAAAAAAUCAAAAAAAAIA'\
'AAAAAAAAoAUAAAAAAAAUAAAAAAAAAAcAAAAAAAAAFwAAAAAAAABIGwAAAAAAAAcAAAAAAAAAQBoA'\
'AAAAAAAIAAAAAAAAAAgBAAAAAAAACQAAAAAAAAAYAAAAAAAAAP7//28AAAAAEBoAAAAAAAD///9v'\
'AAAAAAEAAAAAAAAA8P//bwAAAAA0GQAAAAAAAPn//28AAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAADgTSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmIQAAAAAAADYhAAAAAAAA'\
'RiEAAAAAAABWIQAAAAAAAGYhAAAAAAAAdiEAAAAAAACGIQAAAAAAAJYhAAAAAAAApiEAAAAAAAC2'\
'IQAAAAAAAMYhAAAAAAAA1iEAAAAAAADmIQAAAAAAAPYhAAAAAAAABiIAAAAAAAAWIgAAAAAAACYi'\
'AAAAAAAANiIAAAAAAABGIgAAAAAAAFYiAAAAAAAAZiIAAAAAAAB2IgAAAAAAAIYiAAAAAAAAliIA'\
'AAAAAACmIgAAAAAAALYiAAAAAAAAxiIAAAAAAADWIgAAAAAAAOYiAAAAAAAA9iIAAAAAAAAGIwAA'\
'AAAAABYjAAAAAAAAJiMAAAAAAAA2IwAAAAAAAEYjAAAAAAAAViMAAAAAAABmIwAAAAAAAHYjAAAA'\
'AAAAhiMAAAAAAACWIwAAAAAAAKYjAAAAAAAAtiMAAAAAAADGIwAAAAAAANYjAAAAAAAA5iMAAAAA'\
'AAD2IwAAAAAAAAYkAAAAAAAAFiQAAAAAAAAmJAAAAAAAADYkAAAAAAAARiQAAAAAAABWJAAAAAAA'\
'AGYkAAAAAAAAdiQAAAAAAACGJAAAAAAAAJYkAAAAAAAApiQAAAAAAAC2JAAAAAAAAMYkAAAAAAAA'\
'1iQAAAAAAAD4USAAAAAAAEdDQzogKFVidW50dSA1LjQuMC02dWJ1bnR1MX4xNi4wNC40KSA1LjQu'\
'MCAyMDE2MDYwOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAQDIAQAAAAAAAAAA'\
'AAAAAAAAAAAAAAMAAgDwAQAAAAAAAAAAAAAAAAAAAAAAAAMAAwBoAwAAAAAAAAAAAAAAAAAAAAAA'\
'AAMABABwDQAAAAAAAAAAAAAAAAAAAAAAAAMABQA0GQAAAAAAAAAAAAAAAAAAAAAAAAMABgAQGgAA'\
'AAAAAAAAAAAAAAAAAAAAAAMABwBAGgAAAAAAAAAAAAAAAAAAAAAAAAMACABIGwAAAAAAAAAAAAAA'\
'AAAAAAAAAAMACQDoIAAAAAAAAAAAAAAAAAAAAAAAAAMACgAQIQAAAAAAAAAAAAAAAAAAAAAAAAMA'\
'CwDgJAAAAAAAAAAAAAAAAAAAAAAAAAMADADwJAAAAAAAAAAAAAAAAAAAAAAAAAMADQB0QQAAAAAA'\
'AAAAAAAAAAAAAAAAAAMADgCAQQAAAAAAAAAAAAAAAAAAAAAAAAMADwAARQAAAAAAAAAAAAAAAAAA'\
'AAAAAAMAEABwRgAAAAAAAAAAAAAAAAAAAAAAAAMAEQDITSAAAAAAAAAAAAAAAAAAAAAAAAMAEgDQ'\
'TSAAAAAAAAAAAAAAAAAAAAAAAAMAEwDYTSAAAAAAAAAAAAAAAAAAAAAAAAMAFADgTSAAAAAAAAAA'\
'AAAAAAAAAAAAAAMAFQDATyAAAAAAAAAAAAAAAAAAAAAAAAMAFgAAUCAAAAAAAAAAAAAAAAAAAAAA'\
'AAMAFwD4USAAAAAAAAAAAAAAAAAAAAAAAAMAGAAAUiAAAAAAAAAAAAAAAAAAAAAAAAMAGQAAAAAA'\
'AAAAAAAAAAAAAAAAAQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAADAAAAAEAEwDYTSAAAAAAAAAAAAAA'\
'AAAAGQAAAAIADADwJAAAAAAAAAAAAAAAAAAAGwAAAAIADAAwJQAAAAAAAAAAAAAAAAAALgAAAAIA'\
'DACAJQAAAAAAAAAAAAAAAAAARAAAAAEAGAAAUiAAAAAAAAEAAAAAAAAAUwAAAAEAEgDQTSAAAAAA'\
'AAAAAAAAAAAAegAAAAIADADAJQAAAAAAAAAAAAAAAAAAhgAAAAEAEQDITSAAAAAAAAAAAAAAAAAA'\
'pQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAAsAAAAAIADADwJQAAAAAAAGYAAAAAAAAAxgAAAAIADABW'\
'JgAAAAAAAGAAAAAAAAAA4wAAAAEAGABAVCAAAAAAAPAAAAAAAAAA7QAAAAEAGAAwVSAAAAAAAAQA'\
'AAAAAAAA9QAAAAEAGABAVSAAAAAAAEgNAAAAAAAA/QAAAAEAGACIYiAAAAAAAAQAAAAAAAAADQEA'\
'AAEAGACMYiAAAAAAAAQAAAAAAAAAGAEAAAEAGACQYiAAAAAAAAgAAAAAAAAAIQEAAAEAGACYYiAA'\
'AAAAAAQAAAAAAAAALgEAAAIADAC2JgAAAAAAAGsAAAAAAAAAPQEAAAIADAAhJwAAAAAAAAgEAAAA'\
'AAAAVAEAAAIADAApKwAAAAAAAM8AAAAAAAAAfwEAAAIADACILAAAAAAAAFwCAAAAAAAAkAEAAAIA'\
'DAARPQAAAAAAAAwBAAAAAAAAAQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAAwQEAAAEAEAAwTAAAAAAA'\
'AAAAAAAAAAAAzwEAAAEAEwDYTSAAAAAAAAAAAAAAAAAAAAAAAAQA8f8AAAAAAAAAAAAAAAAAAAAA'\
'2wEAAAEAFwD4USAAAAAAAAAAAAAAAAAA6AEAAAEAFADgTSAAAAAAAAAAAAAAAAAA8QEAAAAADwAA'\
'RQAAAAAAAAAAAAAAAAAABAIAAAEAFwAAUiAAAAAAAAAAAAAAAAAAEAIAAAEAFgAAUCAAAAAAAAAA'\
'AAAAAAAAJgIAABIAAAAAAAAAAAAAAAAAAAAAAAAAOAIAABEAGAAgVCAAAAAAAAQAAAAAAAAAPgIA'\
'ABIADADkLgAAAAAAAHwAAAAAAAAATgIAABIAAAAAAAAAAAAAAAAAAAAAAAAAWgIAABIAAAAAAAAA'\
'AAAAAAAAAAAAAAAAbwIAABIAAAAAAAAAAAAAAAAAAAAAAAAAhAIAACAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAoAIAABIADADdMwAAAAAAAC0AAAAAAAAAzwIAABEAGAAgUyAAAAAAAAABAAAAAAAA1wIAABIA'\
'AAAAAAAAAAAAAAAAAAAAAAAA6wIAABIAAAAAAAAAAAAAAAAAAAAAAAAABQMAABIADABsNAAAAAAA'\
'ADUAAAAAAAAAPwMAABIAAAAAAAAAAAAAAAAAAAAAAAAAUQMAABIADACgNgAAAAAAAD0AAAAAAAAA'\
'qwMAABEAGAAgUiAAAAAAAAABAAAAAAAAswMAABIADAB5NQAAAAAAABoAAAAAAAAA4QMAABAAFwAA'\
'UiAAAAAAAAAAAAAAAAAA6AMAABIADAA5NwAAAAAAAD0AAAAAAAAAHQQAABIAAAAAAAAAAAAAAAAA'\
'AAAAAAAAMQQAABIAAAAAAAAAAAAAAAAAAAAAAAAAUgQAABIADQB0QQAAAAAAAAAAAAAAAAAAWAQA'\
'ABIAAAAAAAAAAAAAAAAAAAAAAAAAbAQAABIAAAAAAAAAAAAAAAAAAAAAAAAAhQQAABIAAAAAAAAA'\
'AAAAAAAAAAAAAAAAoQQAABIADAAdPgAAAAAAAFUDAAAAAAAA0gQAABIAAAAAAAAAAAAAAAAAAAAA'\
'AAAA5gQAABIADADXNQAAAAAAACIAAAAAAAAAHQUAABIAAAAAAAAAAAAAAAAAAAAAAAAAQQUAABIA'\
'AAAAAAAAAAAAAAAAAAAAAAAAXQUAABIAAAAAAAAAAAAAAAAAAAAAAAAAagUAABIAAAAAAAAAAAAA'\
'AAAAAAAAAAAAjQUAABIAAAAAAAAAAAAAAAAAAAAAAAAAoQUAABIAAAAAAAAAAAAAAAAAAAAAAAAA'\
'vwUAABIAAAAAAAAAAAAAAAAAAAAAAAAAHgQAABIAAAAAAAAAAAAAAAAAAAAAAAAA3AUAABIADAC1'\
'NQAAAAAAACIAAAAAAAAAEwYAABIAAAAAAAAAAAAAAAAAAAAAAAAALAYAABIADAD4NgAAAAAAAEEA'\
'AAAAAAAAbQYAABIAAAAAAAAAAAAAAAAAAAAAAAAAfwYAABIAAAAAAAAAAAAAAAAAAAAAAAAAkgYA'\
'ABIAAAAAAAAAAAAAAAAAAAAAAAAApAYAABIAAAAAAAAAAAAAAAAAAAAAAAAAuAYAABIADADdNgAA'\
'AAAAABsAAAAAAAAA9AYAABIADABALAAAAAAAAEgAAAAAAAAAIAcAABIADABgLwAAAAAAAJkBAAAA'\
'AAAAMQcAABIADAD4KwAAAAAAAEgAAAAAAAAAXAcAABEAGAAkVCAAAAAAAAQAAAAAAAAAYgcAACAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAcQcAABIAAAAAAAAAAAAAAAAAAAAAAAAAhQcAABIADAAZOAAAAAAA'\
'AGsAAAAAAAAAuwcAABIAAAAAAAAAAAAAAAAAAAAAAAAA0QcAABIADABJMwAAAAAAACoAAAAAAAAA'\
'5gcAABIADABUNQAAAAAAACUAAAAAAAAAEwgAABIAAAAAAAAAAAAAAAAAAAAAAAAALwgAABIAAAAA'\
'AAAAAAAAAAAAAAAAAAAARggAABIAAAAAAAAAAAAAAAAAAAAAAAAAYggAABIADAAsNQAAAAAAACgA'\
'AAAAAAAAnwgAABIADACEOAAAAAAAAGkAAAAAAAAA1ggAABIAAAAAAAAAAAAAAAAAAAAAAAAA6ggA'\
'ABIADAAuNgAAAAAAADUAAAAAAAAARAkAABIAAAAAAAAAAAAAAAAAAAAAAAAAXwkAABIADAB2NwAA'\
'AAAAAD4AAAAAAAAAmwkAABIAAAAAAAAAAAAAAAAAAAAAAAAAsAkAABIADAD5MAAAAAAAAFACAAAA'\
'AAAAwQkAABAAGACgYiAAAAAAAAAAAAAAAAAAxgkAABIADAB7OQAAAAAAAJYDAAAAAAAA9wkAABIA'\
'AAAAAAAAAAAAAAAAAAAAAAAAEAoAABIADABjNgAAAAAAAD0AAAAAAAAAZAoAABIAAAAAAAAAAAAA'\
'AAAAAAAAAAAAgwoAABIADAAKNAAAAAAAAC0AAAAAAAAAsAoAABAAGAAAUiAAAAAAAAAAAAAAAAAA'\
'vAoAABIAAAAAAAAAAAAAAAAAAAAAAAAA3AoAABIADABzMwAAAAAAAGoAAAAAAAAA7QoAABIADADG'\
'NAAAAAAAACIAAAAAAAAAIQsAABIAAAAAAAAAAAAAAAAAAAAAAAAARwsAABIAAAAAAAAAAAAAAAAA'\
'AAAAAAAAWwsAABIADAA3NAAAAAAAADUAAAAAAAAAkQsAABIAAAAAAAAAAAAAAAAAAAAAAAAAowsA'\
'ABIAAAAAAAAAAAAAAAAAAAAAAAAArwsAABIAAAAAAAAAAAAAAAAAAAAAAAAAuwsAABIAAAAAAAAA'\
'AAAAAAAAAAAAAAAAWgwAABIAAAAAAAAAAAAAAAAAAAAAAAAA2AsAABIADAD5NQAAAAAAADUAAAAA'\
'AAAAKgwAABIAAAAAAAAAAAAAAAAAAAAAAAAAQgwAABIAAAAAAAAAAAAAAAAAAAAAAAAAWQwAABIA'\
'AAAAAAAAAAAAAAAAAAAAAAAAbAwAABIADACTNQAAAAAAACIAAAAAAAAAowwAABIAAAAAAAAAAAAA'\
'AAAAAAAAAAAAtwwAACAAAAAAAAAAAAAAAAAAAAAAAAAAywwAABIAAAAAAAAAAAAAAAAAAAAAAAAA'\
'4AwAABIAAAAAAAAAAAAAAAAAAAAAAAAA+AwAABIAAAAAAAAAAAAAAAAAAAAAAAAACg0AABIAAAAA'\
'AAAAAAAAAAAAAAAAAAAAHg0AACAAAAAAAAAAAAAAAAAAAAAAAAAAOA0AABIADAC0NwAAAAAAAGUA'\
'AAAAAAAAcg0AABIADADoNAAAAAAAACIAAAAAAAAApA0AABIADAChNAAAAAAAACUAAAAAAAAA2Q0A'\
'ABIADAAKNQAAAAAAACIAAAAAAAAADQ4AABIAAAAAAAAAAAAAAAAAAAAAAAAAIA4AACIAAAAAAAAA'\
'AAAAAAAAAAAAAAAAtQsAABIACQDoIAAAAAAAAAAAAAAAAAAAPA4AABIAAAAAAAAAAAAAAAAAAAAA'\
'AAAAVg4AABIADAA0OQAAAAAAAEcAAAAAAAAAkQ4AABEAAAAAAAAAAAAAAAAAAAAAAAAApQ4AABIA'\
'DADtOAAAAAAAAEcAAAAAAAAAAGNydHN0dWZmLmMAX19KQ1JfTElTVF9fAGRlcmVnaXN0ZXJfdG1f'\
'Y2xvbmVzAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuNzU4NQBfX2RvX2dsb2JhbF9k'\
'dG9yc19hdXhfZmluaV9hcnJheV9lbnRyeQBmcmFtZV9kdW1teQBfX2ZyYW1lX2R1bW15X2luaXRf'\
'YXJyYXlfZW50cnkAbGliY3l1c2IuYwBsaWJ1c2JfZ2V0X2Rlc2NyaXB0b3IAbGlidXNiX2dldF9z'\
'dHJpbmdfZGVzY3JpcHRvcgBfWkw1Y3lkZXYAX1pMM25pZABfWkwzdnBkAF9aTDEwbWF4ZGV2aWNl'\
'cwBfWkw2bnVtZGV2AF9aTDRsaXN0AF9aTDhjaGVja3N1bQBfWkw3aXNlbXB0eVBjaQBfWkwxNnBh'\
'cnNlX2NvbmZpZ2ZpbGV2AF9aTDIxZGV2aWNlX2lzX29mX2ludGVyZXN0UDEzbGlidXNiX2Rldmlj'\
'ZQBfWkwxMHJlbnVtZXJhdGV2AF9aTDE2Y29udHJvbF90cmFuc2ZlclAyMGxpYnVzYl9kZXZpY2Vf'\
'aGFuZGxlalBoaQBfX0ZSQU1FX0VORF9fAF9fSkNSX0VORF9fAF9fZHNvX2hhbmRsZQBfRFlOQU1J'\
'QwBfX0dOVV9FSF9GUkFNRV9IRFIAX19UTUNfRU5EX18AX0dMT0JBTF9PRkZTRVRfVEFCTEVfAGZy'\
'ZWVAQEdMSUJDXzIuMi41AGxvZ2ZkAF9aMTBjeXVzYl9vcGVudgBsaWJ1c2Jfb3BlbgBzdHJuY3B5'\
'QEBHTElCQ18yLjIuNQBzdHJuY21wQEBHTElCQ18yLjIuNQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25l'\
'VGFibGUAX1oxOWN5dXNiX2dldF9idXNudW1iZXJQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZQBsb2dm'\
'aWxlAHN0cmNweUBAR0xJQkNfMi4yLjUAbGlidXNiX2ludGVycnVwdF90cmFuc2ZlcgBfWjI5Y3l1'\
'c2JfZ2V0X21heF9pc29fcGFja2V0X3NpemVQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWgAcHV0c0BA'\
'R0xJQkNfMi4yLjUAX1ozNmN5dXNiX2dldF9jb25maWdfZGVzY3JpcHRvcl9ieV92YWx1ZVAyMGxp'\
'YnVzYl9kZXZpY2VfaGFuZGxlaFBQMjF1c2JfY29uZmlnX2Rlc2NyaXB0b3IAcGlkZmlsZQBfWjE4'\
'Y3l1c2JfcmVzZXRfZGV2aWNlUDIwbGlidXNiX2RldmljZV9oYW5kbGUAX2VkYXRhAF9aMjBjeXVz'\
'Yl9nZXRfZGVzY3JpcHRvclAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaGhQaGkAZmNsb3NlQEBHTElC'\
'Q18yLjIuNQBsaWJ1c2Jfc2V0X2ludGVyZmFjZV9hbHRfc2V0dGluZwBfZmluaQBzdHJsZW5AQEdM'\
'SUJDXzIuMi41AGxpYnVzYl9yZWxlYXNlX2ludGVyZmFjZQBfX3N0YWNrX2Noa19mYWlsQEBHTElC'\
'Q18yLjQAX1oxOGN5dXNiX2Rvd25sb2FkX2Z4M1AyMGxpYnVzYl9kZXZpY2VfaGFuZGxlUEtjAHBy'\
'aW50ZkBAR0xJQkNfMi4yLjUAX1oyNmN5dXNiX2F0dGFjaF9rZXJuZWxfZHJpdmVyUDIwbGlidXNi'\
'X2RldmljZV9oYW5kbGVpAGxpYnVzYl9nZXRfYWN0aXZlX2NvbmZpZ19kZXNjcmlwdG9yAGxpYnVz'\
'Yl9kZXRhY2hfa2VybmVsX2RyaXZlcgBsaWJ1c2JfY2xvc2UAbGlidXNiX2dldF9zdHJpbmdfZGVz'\
'Y3JpcHRvcl9hc2NpaQBtZW1zZXRAQEdMSUJDXzIuMi41AGxpYnVzYl9mcmVlX2NvbmZpZ19kZXNj'\
'cmlwdG9yAGxpYnVzYl9nZXRfY29uZmlnX2Rlc2NyaXB0b3IAX1oyNmN5dXNiX2RldGFjaF9rZXJu'\
'ZWxfZHJpdmVyUDIwbGlidXNiX2RldmljZV9oYW5kbGVpAGxpYnVzYl9nZXRfY29uZmlndXJhdGlv'\
'bgBfWjMzY3l1c2JfZ2V0X3N0cmluZ19kZXNjcmlwdG9yX2FzY2lpUDIwbGlidXNiX2RldmljZV9o'\
'YW5kbGVoUGhpAHJlYWRAQEdMSUJDXzIuMi41AGZnZXRzQEBHTElCQ18yLjIuNQBsaWJ1c2JfY2xl'\
'YXJfaGFsdABzdHJjbXBAQEdMSUJDXzIuMi41AF9aMjhjeXVzYl9mcmVlX2NvbmZpZ19kZXNjcmlw'\
'dG9yUDI0bGlidXNiX2NvbmZpZ19kZXNjcmlwdG9yAF9aMTZjeXVzYl9nZXRwcm9kdWN0UDIwbGli'\
'dXNiX2RldmljZV9oYW5kbGUAX1oxMGN5dXNiX29wZW50dABfWjE1Y3l1c2JfZ2V0dmVuZG9yUDIw'\
'bGlidXNiX2RldmljZV9oYW5kbGUAcGlkZmQAX19nbW9uX3N0YXJ0X18Ac3RydG9sQEBHTElCQ18y'\
'LjIuNQBfWjE4Y3l1c2JfY29udHJvbF9yZWFkUDIwbGlidXNiX2RldmljZV9oYW5kbGVoaHR0UGh0'\
'agBsaWJ1c2JfZ2V0X2J1c19udW1iZXIAX1oxNWN5dXNiX2dldGhhbmRsZWkAX1oxNmN5dXNiX2Ns'\
'ZWFyX2hhbHRQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWgAbGlidXNiX2F0dGFjaF9rZXJuZWxfZHJp'\
'dmVyAGxpYnVzYl9nZXRfZGV2aWNlX2xpc3QAbGlidXNiX2tlcm5lbF9kcml2ZXJfYWN0aXZlAF9a'\
'MzFjeXVzYl9zZXRfaW50ZXJmYWNlX2FsdF9zZXR0aW5nUDIwbGlidXNiX2RldmljZV9oYW5kbGVp'\
'aQBfWjE5Y3l1c2JfY29udHJvbF93cml0ZVAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaGh0dFBodGoA'\
'bWFsbG9jQEBHTElCQ18yLjIuNQBfWjM0Y3l1c2JfZ2V0X2FjdGl2ZV9jb25maWdfZGVzY3JpcHRv'\
'clAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlUFAyNGxpYnVzYl9jb25maWdfZGVzY3JpcHRvcgBsaWJ1'\
'c2JfZ2V0X21heF9wYWNrZXRfc2l6ZQBfWjI3Y3l1c2JfZ2V0X3N0cmluZ19kZXNjcmlwdG9yUDIw'\
'bGlidXNiX2RldmljZV9oYW5kbGVodFBoaQBsaWJ1c2JfYnVsa190cmFuc2ZlcgBfWjExY3l1c2Jf'\
'ZXJyb3JpAF9lbmQAX1oxOGN5dXNiX2Rvd25sb2FkX2Z4MlAyMGxpYnVzYl9kZXZpY2VfaGFuZGxl'\
'UGNoAGxpYnVzYl9zZXRfY29uZmlndXJhdGlvbgBfWjI3Y3l1c2JfZ2V0X2NvbmZpZ19kZXNjcmlw'\
'dG9yUDIwbGlidXNiX2RldmljZV9oYW5kbGVoUFAyNGxpYnVzYl9jb25maWdfZGVzY3JpcHRvcgBs'\
'aWJ1c2JfZ2V0X21heF9pc29fcGFja2V0X3NpemUAX1oxN2N5dXNiX2dldF9kZXZhZGRyUDIwbGli'\
'dXNiX2RldmljZV9oYW5kbGUAX19ic3Nfc3RhcnQAbGlidXNiX29wZW5fZGV2aWNlX3dpdGhfdmlk'\
'X3BpZABfWjExY3l1c2JfY2xvc2V2AF9aMjNjeXVzYl9zZXRfY29uZmlndXJhdGlvblAyMGxpYnVz'\
'Yl9kZXZpY2VfaGFuZGxlaQBsaWJ1c2JfZ2V0X2NvbmZpZ19kZXNjcmlwdG9yX2J5X3ZhbHVlAGxp'\
'YnVzYl9yZXNldF9kZXZpY2UAX1oyNWN5dXNiX2dldF9tYXhfcGFja2V0X3NpemVQMjBsaWJ1c2Jf'\
'ZGV2aWNlX2hhbmRsZWgAbGlidXNiX2dldF9kZXZpY2UAbGlidXNiX2V4aXQAbGlidXNiX2luaXQA'\
'bGlidXNiX2dldF9kZXZpY2VfZGVzY3JpcHRvcgBfWjI3Y3l1c2JfZ2V0X2RldmljZV9kZXNjcmlw'\
'dG9yUDIwbGlidXNiX2RldmljZV9oYW5kbGVQMjRsaWJ1c2JfZGV2aWNlX2Rlc2NyaXB0b3IAbGli'\
'dXNiX2ZyZWVfZGV2aWNlX2xpc3QAbGlidXNiX2NsYWltX2ludGVyZmFjZQBmb3BlbkBAR0xJQkNf'\
'Mi4yLjUAX1oyNmN5dXNiX2tlcm5lbF9kcml2ZXJfYWN0aXZlUDIwbGlidXNiX2RldmljZV9oYW5k'\
'bGVpAHN0cnRva0BAR0xJQkNfMi4yLjUAX0p2X1JlZ2lzdGVyQ2xhc3NlcwBzdHJ0b3VsQEBHTElC'\
'Q18yLjIuNQBsaWJ1c2JfY29udHJvbF90cmFuc2ZlcgBleGl0QEBHTElCQ18yLjIuNQBmd3JpdGVA'\
'QEdMSUJDXzIuMi41AF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX1oyMmN5dXNiX2NvbnRyb2xf'\
'dHJhbnNmZXJQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWhodHRQaHRqAF9aMjFjeXVzYl9jbGFpbV9p'\
'bnRlcmZhY2VQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWkAX1oyM2N5dXNiX2dldF9jb25maWd1cmF0'\
'aW9uUDIwbGlidXNiX2RldmljZV9oYW5kbGVQaQBfWjIzY3l1c2JfcmVsZWFzZV9pbnRlcmZhY2VQ'\
'MjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWkAc2xlZXBAQEdMSUJDXzIuMi41AF9fY3hhX2ZpbmFsaXpl'\
'QEBHTElCQ18yLjIuNQBsaWJ1c2JfZ2V0X2RldmljZV9hZGRyZXNzAF9aMjRjeXVzYl9pbnRlcnJ1'\
'cHRfdHJhbnNmZXJQMjBsaWJ1c2JfZGV2aWNlX2hhbmRsZWhQaGlQaWoAc3RkZXJyQEBHTElCQ18y'\
'LjIuNQBfWjE5Y3l1c2JfYnVsa190cmFuc2ZlclAyMGxpYnVzYl9kZXZpY2VfaGFuZGxlaFBoaVBp'\
'aQAALnN5bXRhYgAuc3RydGFiAC5zaHN0cnRhYgAubm90ZS5nbnUuYnVpbGQtaWQALmdudS5oYXNo'\
'AC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5y'\
'ZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIA'\
'LmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5qY3IALmR5bmFtaWMALmdvdC5wbHQA'\
'LmRhdGEALmJzcwAuY29tbWVudAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAHAAAAAgAAAAAAAADIAQAAAAAA'\
'AMgBAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAuAAAA9v//bwIAAAAAAAAA'\
'8AEAAAAAAADwAQAAAAAAAHgBAAAAAAAAAwAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAOAAAAAsAAAAC'\
'AAAAAAAAAGgDAAAAAAAAaAMAAAAAAAAICgAAAAAAAAQAAAACAAAACAAAAAAAAAAYAAAAAAAAAEAA'\
'AAADAAAAAgAAAAAAAABwDQAAAAAAAHANAAAAAAAAxAsAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA'\
'AAAAAABIAAAA////bwIAAAAAAAAANBkAAAAAAAA0GQAAAAAAANYAAAAAAAAAAwAAAAAAAAACAAAA'\
'AAAAAAIAAAAAAAAAVQAAAP7//28CAAAAAAAAABAaAAAAAAAAEBoAAAAAAAAwAAAAAAAAAAQAAAAB'\
'AAAACAAAAAAAAAAAAAAAAAAAAGQAAAAEAAAAAgAAAAAAAABAGgAAAAAAAEAaAAAAAAAACAEAAAAA'\
'AAADAAAAAAAAAAgAAAAAAAAAGAAAAAAAAABuAAAABAAAAEIAAAAAAAAASBsAAAAAAABIGwAAAAAA'\
'AKAFAAAAAAAAAwAAABYAAAAIAAAAAAAAABgAAAAAAAAAeAAAAAEAAAAGAAAAAAAAAOggAAAAAAAA'\
'6CAAAAAAAAAaAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAHMAAAABAAAABgAAAAAAAAAQ'\
'IQAAAAAAABAhAAAAAAAA0AMAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAB+AAAAAQAAAAYA'\
'AAAAAAAA4CQAAAAAAADgJAAAAAAAABAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAhwAA'\
'AAEAAAAGAAAAAAAAAPAkAAAAAAAA8CQAAAAAAACCHAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA'\
'AAAAAI0AAAABAAAABgAAAAAAAAB0QQAAAAAAAHRBAAAAAAAACQAAAAAAAAAAAAAAAAAAAAQAAAAA'\
'AAAAAAAAAAAAAACTAAAAAQAAAAIAAAAAAAAAgEEAAAAAAACAQQAAAAAAAH8DAAAAAAAAAAAAAAAA'\
'AAAIAAAAAAAAAAAAAAAAAAAAmwAAAAEAAAACAAAAAAAAAABFAAAAAAAAAEUAAAAAAABsAQAAAAAA'\
'AAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAKkAAAABAAAAAgAAAAAAAABwRgAAAAAAAHBGAAAAAAAA'\
'xAUAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAACzAAAADgAAAAMAAAAAAAAAyE0gAAAAAADI'\
'TQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAvwAAAA8AAAADAAAAAAAAANBN'\
'IAAAAAAA0E0AAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAMsAAAABAAAAAwAA'\
'AAAAAADYTSAAAAAAANhNAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADQAAAA'\
'BgAAAAMAAAAAAAAA4E0gAAAAAADgTQAAAAAAAOABAAAAAAAABAAAAAAAAAAIAAAAAAAAABAAAAAA'\
'AAAAggAAAAEAAAADAAAAAAAAAMBPIAAAAAAAwE8AAAAAAABAAAAAAAAAAAAAAAAAAAAACAAAAAAA'\
'AAAIAAAAAAAAANkAAAABAAAAAwAAAAAAAAAAUCAAAAAAAABQAAAAAAAA+AEAAAAAAAAAAAAAAAAA'\
'AAgAAAAAAAAACAAAAAAAAADiAAAAAQAAAAMAAAAAAAAA+FEgAAAAAAD4UQAAAAAAAAgAAAAAAAAA'\
'AAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA6AAAAAgAAAADAAAAAAAAAABSIAAAAAAAAFIAAAAAAACg'\
'EAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAO0AAAABAAAAMAAAAAAAAAAAAAAAAAAAAABS'\
'AAAAAAAANAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAARAAAAAwAAAAAAAAAAAAAAAAAA'\
'AAAAAABzcAAAAAAAAPYAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAIAAAAAAAAA'\
'AAAAAAAAAAAAAAAAOFIAAAAAAABgDwAAAAAAABwAAAA7AAAACAAAAAAAAAAYAAAAAAAAAAkAAAAD'\
'AAAAAAAAAAAAAAAAAAAAAAAAAJhhAAAAAAAA2w4AAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA'\
'AAA=' | tee --append libcyusb.so.2 && base64 --decode libcyusb.so.2 >> libcyusb.so.1 \
&& cp libcyusb.so.1 /usr/local/lib \
&& cp libcyusb.so.1 /usr/lib/x86_64-linux-gnu \
&& rm -rf libcyusb.so.2 \
&& ln -s /usr/local/lib/libcyusb.so.1 /usr/local/lib/libcyusb.so \
&& ln -s /usr/lib/x86_64-linux-gnu/libcyusb.so.1 /usr/lib/x86_64-linux-gnu/libcyusb.so

VOLUME dev/bus/usb:/dev/bus/usb




#
#
# Generate directories tree structure
#
#
RUN mkdir /home/inception \
&& mkdir /home/inception/Analyzer \
&& mkdir /home/inception/compiler \
&& mkdir /home/inception/rt-debugger-driver \
&& mkdir /home/inception/samples \
&& mkdir /home/inception/stubs \
&& mkdir /home/inception/tools \
&& mkdir /home/inception/tools/llvm \
&& mkdir /home/inception/tools/llvm/build_debug \
&& mkdir /home/inception/tools/llvm/build_release
RUN mkdir /home/inception/tools/mbed-cli

#
#
# Configure git, system user and docker workdir
#
#
RUN useradd -ms /bin/bash inception \
&& echo "inception:inception" | chpasswd && adduser inception sudo \
&& chown -R inception:inception /home/inception
WORKDIR /home/inception

USER inception

#
#
# Clone Inception modules
#
#
RUN git clone --branch master https://gitlab.eurecom.fr/nasm/Inception-analyzer.git ./Analyzer \
&& git clone --branch master https://gitlab.eurecom.fr/nasm/Inception-compiler.git ./compiler \
&& git clone --branch master https://gitlab.eurecom.fr/nasm/Inception-debugger-driver.git ./rt-debugger-driver \
&& git clone --branch master https://gitlab.eurecom.fr/nasm/Inception-samples.git ./samples


#
#
# Downloads and install dependencies that are not available as public packages
#
#
# Download LLVM 3.6.2 that is the version supported by Inception
WORKDIR /home/inception/tools/llvm
RUN git clone https://github.com/llvm-mirror/llvm llvm3.6 \
&& cd llvm3.6 \
&& git checkout release_36

# Download Clang 3.6.2 that is the version supported by Inception
RUN cd llvm3.6/tools \
&& git clone https://github.com/llvm-mirror/clang \
&& cd clang && git checkout release_36

# Build LLVM with Clang
RUN cd build_debug \
&& ../llvm3.6/configure --enable-debug-symbols --build=x86_64-linux-gnu \
&& make -j${MAKE_JOBS}

# Install llvm in /usr/local/lib
USER root
RUN cd build_debug && make install
USER inception

# Install mbed cli
USER root
RUN git clone https://github.com/ARMmbed/mbed-cli.git ./mbed-cli
RUN cd ./mbed-cli && python setup.py install
USER inception

WORKDIR /home/inception/tools

#Installing Analyzer (Klee) dependencies
#Installing Minisat
RUN git clone https://github.com/stp/minisat.git ./minisat \
&& cd minisat \
&& mkdir build \
&& cd build \
&& cmake -DSTATIC_BINARIES=ON -DCMAKE_INSTALL_PREFIX=/usr/ ../  \
&& make all

# Install llvm in /usr/local/lib
USER root
RUN cd minisat/build && make install
USER inception

#Installing STP
RUN git clone https://github.com/msoos/cryptominisat ./cryptominisat \
&& cd cryptominisat  \
&& mkdir build  \
&& cd build  \
&& cmake ..  \
&& make

# Install llvm in /usr/local/lib
USER root
RUN cd cryptominisat/build && make install && ldconfig
USER inception

#Installing STP
RUN git clone https://github.com/stp/stp.git stp \
&& cd stp \
&& git checkout tags/2.1.2 \
&& mkdir build \
&& cd build \
&& cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_PYTHON_INTERFACE=OFF .. \
&& make \
&& ulimit -s unlimited

USER root
RUN cd stp/build && make install
USER inception

#Installing klee-uclibc
RUN git clone https://github.com/klee/klee-uclibc.git ./klee-uclibc \
&& cd klee-uclibc \
&& ./configure --with-llvm-config ../llvm/build_debug/Debug+Asserts/bin/llvm-config --make-llvm-lib \
&& make -j${MAKE_JOBS}

#
#
# Install Inception modules
#
#
WORKDIR /home/inception

#Installing Inception-driver
# This is the last stable commit before moving to cmake
RUN cd rt-debugger-driver && git checkout 7524f1371f16fb8230834090d2697e35d1d45018
RUN  cd ./rt-debugger-driver/Debug/ \
&& make all \
&& find . -name "*.o" -and -not -name "main.o" -print0 | xargs -0 ar crv libinception.a

USER root
RUN cd ./rt-debugger-driver/Debug \
&& GCC_VERSION="$(gcc -dumpversion)" \
&& cp libinception.a /usr/lib/gcc/x86_64-linux-gnu/$GCC_VERSION/libinception.a
USER inception

#Installing Analyzer
ARG LLVM_VERSION=3.6
RUN cd ./Analyzer \
&& DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" \
&& ./autoconf/AutoRegen.sh ../tools/llvm/llvm3.6/ \
&& CXXFLAGS="-g3 -O0 -fexceptions" CFLAGS="-g3 -O0" ./configure \
            --enable-cxx11 \
            --with-stp=$DIR/../tools/stp/ \
            --enable-posix-runtime \
            --with-llvmsrc=$DIR/../tools/llvm/llvm$LLVM_VERSION \
            --with-llvmobj=$DIR/../tools/llvm/build_debug \
            --with-llvmcc=$DIR/../tools/llvm/build_debug/Debug+Asserts/bin/clang \
            --with-llvmcxx=$DIR/../tools/llvm/build_debug/Debug+Asserts/bin/clang++ \
            --with-runtime='Debug+Asserts' \
	    --with-llvm-build-mode='Debug+Asserts' \
&& make -j${MAKE_JOBS} all

USER root
RUN cd ./Analyzer && make install
USER inception

# This is the current working commit with the cmake toolchain
RUN mkdir ./compiler/build
RUN cd ./compiler/build && cmake ../ && make -j${MAKE_JOBS} 

USER root
RUN cd ./compiler/build && make install
USER inception

RUN echo "Credits :" \
&& echo "Author : G. Camurati and N. Corteggiani" \
&& echo "ID     : Inception" \
&& echo "Year   : 2016/2017" \
&& echo "Status : Release" \
&& echo " Enjoy !"


CMD ["echo","Home directory $HOME"]
CMD ["echo","Workspace directory $HOME/projects"]
CMD ["echo","Welcome to the Inception framework !"]
